--
-- awr_trend.sql -- AWR Timeline Comparison (driver)
-- =====================================================================
--
-- Oracle 19c only (Diagnostic + Tuning Pack licensed).  Pure SQL*Plus.
--
-- Usage (two modes):
--
--   1. Defaults:
--        sqlplus user/pw@svc @awr_trend.sql
--
--   2. Override via DEFINE before calling (recommended for custom windows):
--        sqlplus user/pw@svc
--        SQL> DEFINE target_end = '2026-04-15 09:00'
--        SQL> DEFINE win_hours  = 2
--        SQL> DEFINE weeks_back = 6
--        SQL> @awr_trend.sql
--
-- Substitution variables (with defaults):
--   target_end   'AUTO' (prior full hour) or 'YYYY-MM-DD HH24:MI'
--   win_hours    1
--   weeks_back   4
--   top_n        10
--   inst_num     0 = aggregate across RAC; otherwise the instance number
--
-- Prerequisite (run once per target database, as the owner user):
--   sqlplus user/pw@svc @sql/setup_schema.sql
--
-- Output: reports/awr_trend_<DBID>_<YYYYMMDDHH24MI>_run<run_id>.html
--

SET ECHO          OFF
SET VERIFY        OFF
SET FEEDBACK      OFF
SET HEADING       OFF
SET TERMOUT       OFF
SET TRIMSPOOL     ON
SET TRIMOUT       ON
SET PAGESIZE      0
SET LINESIZE      32767
SET LONG          200000
SET LONGCHUNKSIZE 200000
SET NUMWIDTH      20
SET DEFINE        '~'
SET SQLBLANKLINES ON
SET SERVEROUTPUT  ON SIZE UNLIMITED FORMAT WRAPPED

WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR  EXIT FAILURE

-- The caller MUST have set target_end / win_hours / weeks_back / top_n /
-- inst_num before invoking this driver.  For the canonical defaults, do:
--     @sql/defaults.sql
-- before @awr_trend.sql.  The shell wrapper run_awr_trend.sh does this
-- automatically, so a bare `./run_awr_trend.sh user/pw@svc` works too.
-- We do NOT DEFINE them here to avoid clobbering an explicit caller override.

-- Allocate run_id and build report path --------------------------------
COLUMN run_id       NEW_VALUE run_id       NOPRINT
COLUMN report_path  NEW_VALUE report_path  NOPRINT

SELECT awr_trend_run_seq.NEXTVAL AS run_id FROM dual;

SELECT 'reports/awr_trend_'
       || (SELECT dbid FROM v$database) || '_'
       || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MI') || '_run'
       || ~run_id || '.html' AS report_path
FROM dual;

SPOOL ~report_path

-- -------------------------------------------------------------------
-- HTML prologue
-- -------------------------------------------------------------------
BEGIN
    DBMS_OUTPUT.PUT_LINE('<!DOCTYPE html>');
    DBMS_OUTPUT.PUT_LINE('<html lang="en"><head><meta charset="utf-8">');
    DBMS_OUTPUT.PUT_LINE('<meta name="viewport" content="width=device-width, initial-scale=1">');
    DBMS_OUTPUT.PUT_LINE('<title>AWR Timeline Comparison &mdash; run '
        || ~run_id || '</title>');
END;
/

@@sql/_style.sql

BEGIN
    DBMS_OUTPUT.PUT_LINE('</head><body>');
END;
/

-- -------------------------------------------------------------------
-- Sections (order matters: 07 must run last because it reads facts
-- inserted by 02-06).  Section 00 inserts the AWR_TREND_RUNS row.
-- -------------------------------------------------------------------
@@sql/00_params.sql
@@sql/01_windows.sql
@@sql/02_load_profile.sql
@@sql/03_sysmetric.sql
@@sql/04_waits_fg.sql
@@sql/05_waits_bg.sql
@@sql/06_top_sql.sql
@@sql/07_summary.sql

-- -------------------------------------------------------------------
-- HTML epilogue
-- -------------------------------------------------------------------
BEGIN
    DBMS_OUTPUT.PUT_LINE('<footer class="report">');
    DBMS_OUTPUT.PUT_LINE('Generated by awr_trend.sql &mdash; run ' || ~run_id
        || ' &mdash; raw data preserved in the AWR_TREND_* scratch tables.');
    DBMS_OUTPUT.PUT_LINE('</footer>');
    DBMS_OUTPUT.PUT_LINE('</body></html>');
END;
/

SPOOL OFF

SET TERMOUT  ON
SET FEEDBACK ON
SET HEADING  ON
SET PAGESIZE 14

PROMPT
PROMPT ============================================================
PROMPT  Report written to: ~report_path
PROMPT  Run id: ~run_id
PROMPT
PROMPT  Query scratch schema for this run:
PROMPT    SELECT severity, metric_name, current_value, prior_mean, z_score
PROMPT    FROM   awr_trend_findings
PROMPT    WHERE  run_id = ~run_id
PROMPT    ORDER BY
PROMPT      CASE severity
PROMPT        WHEN 'CRITICAL' THEN 1 WHEN 'WARN' THEN 2
PROMPT        WHEN 'INSUFFICIENT_HISTORY' THEN 3
PROMPT        WHEN 'FLAT_BASELINE' THEN 4 ELSE 5 END,
PROMPT      ABS(NVL(z_score,0)) DESC;
PROMPT ============================================================
PROMPT

WHENEVER SQLERROR CONTINUE
