--
-- fleet/ddl/10_control_plane.sql
--
-- Control-plane tables for the AWR Fleet Warehouse: the registry of Targets,
-- the per-(Target,DBID) collection high-water marks, the analysis high-water
-- mark, run/error logs, Target Health, and the Metric Profiles.
--
-- Run as the warehouse owner (e.g. AWRWH) on the central 19c Warehouse.
-- Everything here is WAREHOUSE-side. Sources are never written to.
--
-- Glossary terms (see CONTEXT.md): Target, DBID set, High-water mark,
-- Metric Profile, Target Health.
--

-- A Target = a monitored database, the unit of identity (CONTEXT.md: Target).
-- Identity is surface-assigned and stable; it never derives from DBID or name.
CREATE TABLE awrw_target (
    target_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    target_name       VARCHAR2(128)  NOT NULL,
    db_link           VARCHAR2(128)  NOT NULL,   -- read-only Connection to ONE container
    profile_name      VARCHAR2(64)   DEFAULT 'DEFAULT' NOT NULL,
    snap_interval_min NUMBER         DEFAULT 60 NOT NULL,  -- expected AWR snapshot cadence
    enabled           CHAR(1)        DEFAULT 'Y' NOT NULL,
    notes             VARCHAR2(4000),
    created_ts        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT awrw_target_pk        PRIMARY KEY (target_id),
    CONSTRAINT awrw_target_uk        UNIQUE (target_name),
    CONSTRAINT awrw_target_enabled_ck CHECK (enabled IN ('Y','N'))
);

-- A Target owns a set of DBIDs (CONTEXT.md: DBID set), auto-discovered through
-- its Connection. The PK on dbid enforces the Q2 collision guard: a DBID can
-- belong to exactly one Target -- a second Target discovering the same DBID
-- fails the insert and is logged, never silently merged.
CREATE TABLE awrw_dbid (
    dbid          NUMBER     NOT NULL,
    target_id     NUMBER     NOT NULL,
    first_seen_ts TIMESTAMP  DEFAULT SYSTIMESTAMP NOT NULL,
    last_seen_ts  TIMESTAMP  DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT awrw_dbid_pk        PRIMARY KEY (dbid),
    CONSTRAINT awrw_dbid_target_fk FOREIGN KEY (target_id) REFERENCES awrw_target (target_id)
);
CREATE INDEX awrw_dbid_target_ix ON awrw_dbid (target_id);

-- Collection high-water mark: highest fully-collected snap_id per (Target,DBID).
-- One per DBID sequence (snap_id resets per DBID), never per view or instance.
CREATE TABLE awrw_hwm (
    target_id        NUMBER    NOT NULL,
    dbid             NUMBER    NOT NULL,
    last_snap_id     NUMBER    DEFAULT 0 NOT NULL,
    last_snap_end_ts TIMESTAMP,
    updated_ts       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT awrw_hwm_pk PRIMARY KEY (target_id, dbid)
);

-- Analysis high-water mark: last Period (window_end_ts) scored per Target.
-- Each Period is scored exactly once; a Period whose Baseline is not yet
-- present is simply not advanced past (deferred, not failed).
CREATE TABLE awrw_analysis_hwm (
    target_id          NUMBER    NOT NULL,
    last_period_end_ts TIMESTAMP,
    updated_ts         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT awrw_analysis_hwm_pk PRIMARY KEY (target_id)
);

-- One row per phase invocation: the "what is happening" spine.
CREATE TABLE awrw_run_log (
    run_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    target_id   NUMBER,
    phase       VARCHAR2(32) NOT NULL,   -- DISCOVER | COLLECT | ANALYZE | NOTIFY | PURGE
    started_ts  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ended_ts    TIMESTAMP,
    rows_loaded NUMBER,
    status      VARCHAR2(16),            -- RUNNING | OK | ERROR | SKIPPED
    detail      VARCHAR2(4000),
    CONSTRAINT awrw_run_log_pk PRIMARY KEY (run_id)
);
CREATE INDEX awrw_run_log_tgt_ix ON awrw_run_log (target_id, started_ts);

CREATE TABLE awrw_error_log (
    err_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    run_id    NUMBER,
    target_id NUMBER,
    phase     VARCHAR2(32),
    ora_code  NUMBER,
    err_text  VARCHAR2(4000),
    err_ts    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT awrw_error_log_pk PRIMARY KEY (err_id)
);
CREATE INDEX awrw_error_log_tgt_ix ON awrw_error_log (target_id, err_ts);

-- Target Health: collection + analysis freshness, kept OUT of the Finding
-- stream. Drives the Digest coverage section so "silence" can never read as
-- "healthy" -- only Current + scored + quiet does.
CREATE TABLE awrw_target_health (
    target_id           NUMBER NOT NULL,
    last_collect_ok_ts  TIMESTAMP,
    last_snap_end_ts    TIMESTAMP,
    collect_status      VARCHAR2(16),  -- CURRENT | LAGGING | STALE | UNREACHABLE
    consecutive_fail    NUMBER DEFAULT 0 NOT NULL,
    last_analyze_period TIMESTAMP,
    analyze_status      VARCHAR2(16),  -- CURRENT | LAGGING | STALE
    updated_ts          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT awrw_target_health_pk PRIMARY KEY (target_id)
);

-- A Metric Profile = the named, per-metric scoring config (CONTEXT.md). Profile
-- header carries the fleet-wide thresholds and window shape.
CREATE TABLE awrw_profile (
    profile_name VARCHAR2(64) NOT NULL,
    description  VARCHAR2(400),
    z_crit       NUMBER DEFAULT 3  NOT NULL,   -- |z| > z_crit  => CRITICAL
    z_warn       NUMBER DEFAULT 2  NOT NULL,   -- |z| > z_warn  => WARN
    pct_floor    NUMBER DEFAULT 25 NOT NULL,   -- default %-delta floor (per-metric can override)
    weeks_back   NUMBER DEFAULT 4  NOT NULL,   -- Baseline depth (number of prior windows)
    win_hours    NUMBER DEFAULT 1  NOT NULL,   -- Comparison Window width
    step_days    NUMBER DEFAULT 7  NOT NULL,   -- cadence between windows (7 = same hour-of-week)
    fire_consec  NUMBER DEFAULT 2  NOT NULL,   -- hysteresis: consec anomalous Periods to fire
    clear_consec NUMBER DEFAULT 3  NOT NULL,   -- hysteresis: consec normal Periods to clear
    sql_top_n    NUMBER DEFAULT 50 NOT NULL,   -- SQL breadth captured per Snapshot
    -- Regression Detector knobs (top SQL / wait / segment movers vs Baseline).
    -- z_crit/z_warn/weeks_back/win_hours/step_days above are shared with seasonal.
    reg_top_n        NUMBER DEFAULT 10     NOT NULL, -- max regression Findings per subject_type per Period
    reg_sql_min_sec  NUMBER DEFAULT 5      NOT NULL, -- SQL must add >= this many elapsed seconds to qualify
    reg_wait_min_sec NUMBER DEFAULT 30     NOT NULL, -- wait event must add >= this many seconds of wait
    reg_seg_min_blk  NUMBER DEFAULT 100000 NOT NULL, -- segment must do >= this many physical I/O blocks
    CONSTRAINT awrw_profile_pk PRIMARY KEY (profile_name),
    -- window shape must be sane: dur_sec>0 (no /0 in per-second rates), >=1 Baseline window
    CONSTRAINT awrw_profile_win_ck   CHECK (win_hours  > 0),
    CONSTRAINT awrw_profile_weeks_ck CHECK (weeks_back >= 1),
    CONSTRAINT awrw_profile_step_ck  CHECK (step_days  > 0)
);

-- Per-metric scoring config + noise gates. This is the single tuning surface:
-- abs_floor / pct_floor kill idle-DB false positives; polarity tags direction;
-- headline flags the hero-six health line; is_additive drives RAC roll-up.
CREATE TABLE awrw_profile_metric (
    profile_name VARCHAR2(64)  NOT NULL,
    domain       VARCHAR2(16)  NOT NULL,   -- LOAD | METRIC | WAIT
    metric_name  VARCHAR2(128) NOT NULL,
    is_additive  CHAR(1)       DEFAULT 'Y' NOT NULL,  -- Y: SUM across RAC; N: AVG
    abs_floor    NUMBER        DEFAULT 0 NOT NULL,    -- min current value to alert
    pct_floor    NUMBER,                              -- NULL => profile default
    polarity     VARCHAR2(4)   DEFAULT 'BOTH' NOT NULL, -- UP | DOWN | BOTH (which direction alerts)
    headline     CHAR(1)       DEFAULT 'N' NOT NULL,  -- part of the hero-six health line
    CONSTRAINT awrw_profile_metric_pk PRIMARY KEY (profile_name, domain, metric_name),
    CONSTRAINT awrw_profile_metric_fk FOREIGN KEY (profile_name) REFERENCES awrw_profile (profile_name),
    CONSTRAINT awrw_pm_additive_ck CHECK (is_additive IN ('Y','N')),
    CONSTRAINT awrw_pm_polarity_ck CHECK (polarity IN ('UP','DOWN','BOTH')),
    CONSTRAINT awrw_pm_headline_ck CHECK (headline  IN ('Y','N'))
);

-- A Target must reference a Profile that exists (added after awrw_profile is
-- defined above). Guards against a typo'd profile_name silently disabling a
-- Target's analysis (score_period joins target -> profile). 00_drop.sql drops
-- awrw_profile with CASCADE CONSTRAINTS to undo this.
ALTER TABLE awrw_target ADD CONSTRAINT awrw_target_profile_fk
    FOREIGN KEY (profile_name) REFERENCES awrw_profile (profile_name);
