--
-- fleet/ddl/40_findings.sql
--
-- Analysis output: the append-only Finding log and the per-Subject Alert State
-- that drives edge + hysteresis dedup. All three Detectors (seasonal anomaly,
-- top regression, headline) write here via the subject_type/subject_id
-- discriminator, so one pipeline serves all (CONTEXT.md: Finding, Subject,
-- Alert, Alert State, Detector).
--

-- A Finding = a notable observation about one Subject on one Target at one
-- Period. Append-only; this is the queryable "what was ever anomalous" history.
-- Scores that are OK / insufficient-history / flat-baseline are NOT written.
CREATE TABLE awrw_findings (
    finding_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    target_id      NUMBER        NOT NULL,
    dbid           NUMBER,
    detector       VARCHAR2(16)  NOT NULL,   -- SEASONAL | REGRESSION | HEADLINE
    subject_type   VARCHAR2(12)  NOT NULL,   -- metric | sql | wait | segment
    subject_id     VARCHAR2(256) NOT NULL,   -- metric name, sql_id, event, seg_name
    metric_domain  VARCHAR2(16),             -- LOAD | METRIC | WAIT (for metric subjects)
    period_end_ts  TIMESTAMP     NOT NULL,   -- the Period (window_end_ts)
    cur_val        NUMBER,
    prior_mean     NUMBER,
    prior_sd       NUMBER,
    n_prior        NUMBER,
    z_score        NUMBER,
    pct_delta      NUMBER,
    impact         NUMBER,                   -- regression magnitude (e.g. DB-time seconds added)
    direction      VARCHAR2(4)   NOT NULL,   -- UP | DOWN (always set: only CRIT/WARN scores are written)
    severity       VARCHAR2(20)  NOT NULL,   -- CRITICAL | WARN
    plan_changed   CHAR(1)       DEFAULT 'N' NOT NULL,  -- SQL regression: plan flip flag
    created_ts     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT awrw_findings_pk PRIMARY KEY (finding_id),
    CONSTRAINT awrw_findings_sev_ck   CHECK (severity IN ('CRITICAL','WARN')),
    CONSTRAINT awrw_findings_dir_ck   CHECK (direction IN ('UP','DOWN')),
    CONSTRAINT awrw_findings_plan_ck  CHECK (plan_changed IN ('Y','N'))
);
CREATE INDEX awrw_findings_tgt_ix  ON awrw_findings (target_id, period_end_ts);
CREATE INDEX awrw_findings_subj_ix ON awrw_findings (target_id, subject_type, subject_id, period_end_ts);

-- Alert State: per-(Target, Subject) lifecycle that collapses a run of Findings
-- into one fire + one clear. Updated EVERY Period (including normal ones -- that
-- is how a condition clears). The notifier reads edges off this.
CREATE TABLE awrw_alert_state (
    target_id            NUMBER        NOT NULL,
    subject_type         VARCHAR2(12)  NOT NULL,
    subject_id           VARCHAR2(256) NOT NULL,
    state                VARCHAR2(8)   DEFAULT 'NORMAL' NOT NULL, -- FIRING | NORMAL
    severity             VARCHAR2(20),                            -- current firing severity
    consecutive_anom     NUMBER DEFAULT 0 NOT NULL,
    consecutive_normal   NUMBER DEFAULT 0 NOT NULL,
    fired_period_ts      TIMESTAMP,        -- when it last transitioned to FIRING
    cleared_period_ts    TIMESTAMP,        -- when it last transitioned to NORMAL
    last_period_ts       TIMESTAMP,        -- most recent Period evaluated
    last_finding_id      NUMBER,
    notified_fired_ts    TIMESTAMP,        -- last time the FIRING edge was put in a Digest
    notified_cleared_ts  TIMESTAMP,        -- last time the CLEARED edge was put in a Digest
    updated_ts           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT awrw_alert_state_pk PRIMARY KEY (target_id, subject_type, subject_id),
    CONSTRAINT awrw_alert_state_ck CHECK (state IN ('FIRING','NORMAL'))
);
CREATE INDEX awrw_alert_state_fire_ix ON awrw_alert_state (state, severity);
