--
-- sql/lib/js_timeline.plsql
--
-- Client half of the Timeline view (v1.6.0, Mock D): the aligned window
-- grid (#tl, skeleton emitted by sql/00_params.sql, rows by the sections
-- through sql/lib/timeline.plsql), and the "Activity, whole span" charts
-- at the top of every view (section#activity, skeleton in 00; payloads
-- window.AWR_DATA.ashx by wait class and AWR_DATA.ashe by wait event, both
-- from sql/09_ash_timeline.sql's one ASH scan).
-- Emitted once by the driver prologue, right after js_wingrid.plsql (it
-- extends window.AWR_WG); pure inline JS + SVG, CDN-free, so it works
-- offline and with ECharts blocked.  Colours come from CSS variables,
-- except the fixed wait-class palette (window.AWR_WAIT_COLORS,
-- sql/lib/js_wait_colors.plsql) and the event palette (EVP below: CPU
-- keeps the wait-class green, "Other events" a fixed grey).
--
-- Exposes window.AWR_TL:
--   take()        called by the inline script after each section's
--                 <template class="tl-src" data-lane="lane-X">: moves its
--                 rows into that lane (data-after="id" puts a row right
--                 under another one, 18's SQL Monitor rows under 06's) and
--                 unhides the lane.  Runs while the page parses.
--   reveal(el)    opens a folded lane / the "+ Show N more" rows that hide
--                 el (called by the chrome's reveal() before a goTo).
-- and on window.AWR_WG:
--   pin(o)        pin window offset o (0 / null / the pinned one = unpin):
--                 its grid column tints amber, every gutter Delta compares
--                 Current against it ("vs 13 Aug"), the charts' stripe
--                 turns amber; Esc, Current or the gutter's clear unpin it
--                 (a view switch keeps it: the charts show it everywhere).
--   pinned()      the pinned offset or null.
-- At DOMContentLoaded: lane counts / fold / "+ Show N more", the prior
-- values of every grid row (from data-v; shown on hover or pin), the
-- stacked activity columns (Activity lane, and the DB time card chart of
-- the Summary view), then the two Activity charts -- ONE chart factory
-- (mkChart / draw), two instances sharing one time axis (x labels on the
-- lower one, release-marker flags on the upper one): hover crosshair +
-- tooltip with each series' AAS (mirrored on the other chart), legend
-- toggles that restack and rescale, drag-to-zoom with a minimum span
-- (zooms both), Reset / double-click, compared windows shaded -- Current
-- indigo, pinned amber, skipped grey -- click / Enter on one pins it.
-- v1.6.1 series highlight: a legend entry hovered / focused (or kept by a
-- click on its band, Shift+click) is drawn from zero on its own y axis,
-- the rest faded; a class lights its events (AWR_DATA.ashe.ecls) and an
-- event its class; the band under the pointer highlights in place; Esc
-- clears the highlight first, then the pinned window.
-- No literal tilde below (SET DEFINE tilde).  GENERATED: the body below
-- (BEGIN .. END) is written by tools/js2plsql.sh from the readable source
-- sql/lib/src/js_timeline.js -- edit the .js, then run tools/js2plsql.sh
-- (lint check 24 fails on a stale body).  This header is kept as is.
--
BEGIN
    DBMS_OUTPUT.PUT_LINE('<script>');
    DBMS_OUTPUT.PUT_LINE('(function(){');
    DBMS_OUTPUT.PUT_LINE('var doc=document, W=window.AWR_WG=window.AWR_WG||{}, TL=window.AWR_TL={};');
    DBMS_OUTPUT.PUT_LINE('var H1=36e5, MINUS=''\u2212'';');
    DBMS_OUTPUT.PUT_LINE('function $(s,r){return (r||doc).querySelector(s);}');
    DBMS_OUTPUT.PUT_LINE('function $$(s,r){return Array.prototype.slice.call((r||doc).querySelectorAll(s));}');
    DBMS_OUTPUT.PUT_LINE('function shown(el){return !!el&&el.getClientRects().length>0;}');
    DBMS_OUTPUT.PUT_LINE('function mk(t,c,p){var e=doc.createElement(t);if(c)e.className=c;if(p)p.appendChild(e);return e;}');
    DBMS_OUTPUT.PUT_LINE('function esc(s){return String(s==null?'''':s).replace(/[&<>"]/g,function(c){return {''&'':''&amp;'',''<'':''&lt;'',''>'':''&gt;'',''"'':''&quot;''}[c];});}');
    DBMS_OUTPUT.PUT_LINE('function num(s){if(s==null||s==='''')return null;var v=+s;return isNaN(v)?null:v;}');
    DBMS_OUTPUT.PUT_LINE('function nums(s){return String(s||'''').split('','').map(num);}');
    DBMS_OUTPUT.PUT_LINE('function cssNum(el,n,d){var v=parseFloat(getComputedStyle(el).getPropertyValue(n));return isNaN(v)?d:v;}');
    DBMS_OUTPUT.PUT_LINE('function reduced(){try{return matchMedia(''(prefers-reduced-motion: reduce)'').matches;}catch(e){return false;}}');
    DBMS_OUTPUT.PUT_LINE('/* sql/lib/fmt_num.plsql, client side: about 4 significant digits, k / M / G */');
    DBMS_OUTPUT.PUT_LINE('function grp(n){return String(n).replace(/\B(?=(\d{3})+(?!\d))/g,'','');}');
    DBMS_OUTPUT.PUT_LINE('function fmtNum(p){');
    DBMS_OUTPUT.PUT_LINE('  if(p==null)return ''\u2014'';if(p===0)return ''0'';');
    DBMS_OUTPUT.PUT_LINE('  var a=Math.abs(p),s=p<0?''-'':'''',u='''',v=a,t;');
    DBMS_OUTPUT.PUT_LINE('  if(a>=1e9){v=a/1e9;u='' G'';}else if(a>=1e6){v=a/1e6;u='' M'';}else if(a>=1e4){v=a/1e3;u='' k'';}');
    DBMS_OUTPUT.PUT_LINE('  if(v>=1000)t=grp(Math.round(v));else if(v>=100)t=grp(v.toFixed(1));else if(v>=10)t=v.toFixed(2);else if(v>=1)t=v.toFixed(3);');
    DBMS_OUTPUT.PUT_LINE('  else{var d=Math.min(6,3-Math.floor(Math.log10(v)));if(Math.round(v*1e6)===0)return s+''<0.000001'';t=String(+v.toFixed(d));if(t.charAt(0)!==''0'')t=''0''+t.slice(t.indexOf(''.''));}');
    DBMS_OUTPUT.PUT_LINE('  return s+t+u;');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('/* the page''s one Delta rule (sql/lib/band_glyph.plsql delta_span) */');
    DBMS_OUTPUT.PUT_LINE('function delta(cur,mu){');
    DBMS_OUTPUT.PUT_LINE('  if(cur==null||mu==null||mu===0)return ''\u2014'';');
    DBMS_OUTPUT.PUT_LINE('  var q=cur/mu;');
    DBMS_OUTPUT.PUT_LINE('  if(mu>0&&q>=2)return ''\u25b2 \u00d7''+(q<100?q.toFixed(1):Math.round(q));');
    DBMS_OUTPUT.PUT_LINE('  var p=(cur-mu)/Math.abs(mu)*100;');
    DBMS_OUTPUT.PUT_LINE('  return (p>=0?''\u25b2 '':''\u25bc '')+Math.abs(p).toFixed(1)+''%'';');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('function aasTxt(v){return v>=10?v.toFixed(0):v>=1?v.toFixed(1):v>=0.01?v.toFixed(2):v.toPrecision(1);}');
    DBMS_OUTPUT.PUT_LINE('function niceStep(max,n){var raw=max/n,p=Math.pow(10,Math.floor(Math.log10(raw))),m=raw/p;return (m<=1?1:m<=2?2:m<=5?5:10)*p;}');
    DBMS_OUTPUT.PUT_LINE('/* the compared windows, oldest first (window.AWR_WIN from 00_params.sql) */');
    DBMS_OUTPUT.PUT_LINE('function wins(){return (window.AWR_WIN&&window.AWR_WIN.w)||[];}');
    DBMS_OUTPUT.PUT_LINE('function winAt(o){var w=wins();for(var i=0;i<w.length;i++)if(w[i].o===+o)return w[i];return null;}');
    DBMS_OUTPUT.PUT_LINE('function idxOf(o){var w=wins();for(var i=0;i<w.length;i++)if(w[i].o===+o)return i;return -1;}');
    DBMS_OUTPUT.PUT_LINE('function offTxt(w){return w.o===0?''Current'':String(w.l).replace(''-'',MINUS);}');
    DBMS_OUTPUT.PUT_LINE('function wcol(c){return (window.AWR_WAIT_COLORS||{})[c]||''#9AA3AD'';}');
    DBMS_OUTPUT.PUT_LINE('var MON=[''Jan'',''Feb'',''Mar'',''Apr'',''May'',''Jun'',''Jul'',''Aug'',''Sep'',''Oct'',''Nov'',''Dec''],DOW=[''Sun'',''Mon'',''Tue'',''Wed'',''Thu'',''Fri'',''Sat''];');
    DBMS_OUTPUT.PUT_LINE('function PT(s){return Date.parse(String(s).replace('' '',''T'')+'':00Z'');}');
    DBMS_OUTPUT.PUT_LINE('function p2(n){return (n<10?''0'':'''')+n;}');
    DBMS_OUTPUT.PUT_LINE('function fDay(t){var d=new Date(t);return d.getUTCDate()+'' ''+MON[d.getUTCMonth()];}');
    DBMS_OUTPUT.PUT_LINE('function fAt(t){var d=new Date(t);return DOW[d.getUTCDay()]+'' ''+fDay(t)+'' ''+p2(d.getUTCHours())+'':''+p2(d.getUTCMinutes());}');
    DBMS_OUTPUT.PUT_LINE('function fHM(t){var d=new Date(t);return p2(d.getUTCHours())+'':''+p2(d.getUTCMinutes());}');
    DBMS_OUTPUT.PUT_LINE('/* ---- 1. lane sources: a section''s rows ride in <template class="tl-src">,');
    DBMS_OUTPUT.PUT_LINE('   the inline script right after it calls take() while the page parses */');
    DBMS_OUTPUT.PUT_LINE('TL.take=function(){');
    DBMS_OUTPUT.PUT_LINE('  var s=doc.currentScript,t=s&&s.previousElementSibling;');
    DBMS_OUTPUT.PUT_LINE('  if(!t||t.tagName!==''TEMPLATE'')return;');
    DBMS_OUTPUT.PUT_LINE('  var lane=doc.getElementById(t.getAttribute(''data-lane'')),box=lane&&$(''.lrows'',lane);');
    DBMS_OUTPUT.PUT_LINE('  if(!box)return;');
    DBMS_OUTPUT.PUT_LINE('  Array.prototype.slice.call(t.content.children).forEach(function(r){');
    DBMS_OUTPUT.PUT_LINE('    var a=r.getAttribute(''data-after''),ref=a?doc.getElementById(a):null;');
    DBMS_OUTPUT.PUT_LINE('    if(ref&&ref.parentNode===box){');
    DBMS_OUTPUT.PUT_LINE('      while(ref.nextElementSibling&&ref.nextElementSibling.getAttribute(''data-after'')===a)ref=ref.nextElementSibling;');
    DBMS_OUTPUT.PUT_LINE('      box.insertBefore(r,ref.nextElementSibling);');
    DBMS_OUTPUT.PUT_LINE('    }else box.appendChild(r);');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('  lane.hidden=false;');
    DBMS_OUTPUT.PUT_LINE('  t.parentNode.removeChild(t);');
    DBMS_OUTPUT.PUT_LINE('};');
    DBMS_OUTPUT.PUT_LINE('/* open whatever hides a Timeline row: a closed lane, the folded rows */');
    DBMS_OUTPUT.PUT_LINE('TL.reveal=function(el){');
    DBMS_OUTPUT.PUT_LINE('  var lane=el&&el.closest?el.closest(''#tl .lane''):null;if(!lane)return;');
    DBMS_OUTPUT.PUT_LINE('  if(lane.classList.contains(''closed'')){lane.classList.remove(''closed'');var b=$(''.lt2'',lane);if(b)b.setAttribute(''aria-expanded'',''true'');}');
    DBMS_OUTPUT.PUT_LINE('  if(el.classList.contains(''more''))showMore(lane);');
    DBMS_OUTPUT.PUT_LINE('  setTimeout(function(){if(W.render)W.render(lane);},0);');
    DBMS_OUTPUT.PUT_LINE('};');
    DBMS_OUTPUT.PUT_LINE('function showMore(lane){lane.classList.add(''showmore'');var b=$(''.xpb'',lane);if(b)b.setAttribute(''aria-expanded'',''true'');if(W.render)W.render(lane);}');
    DBMS_OUTPUT.PUT_LINE('/* ---- 2. lanes: fold toggles, "+ Show N more", counts in the lane head */');
    DBMS_OUTPUT.PUT_LINE('function laneMeta(lane){');
    DBMS_OUTPUT.PUT_LINE('  var m=$(''.gh2 .meta'',lane);if(!m)return[0,0];');
    DBMS_OUTPUT.PUT_LINE('  var rows=$$(''.lrows > .r'',lane),kind=lane.getAttribute(''data-kind''),h='''',lg=0,md=0,nr=0;');
    DBMS_OUTPUT.PUT_LINE('  rows.forEach(function(r){if(r.classList.contains(''twin'')||r.classList.contains(''xpr''))return;var s=r.getAttribute(''data-sev'');if(s===''large'')lg++;else if(s===''moderate'')md++;else if(s)nr++;});');
    DBMS_OUTPUT.PUT_LINE('  if(kind===''scored''){');
    DBMS_OUTPUT.PUT_LINE('    if(lg)h+=''<span><i class="dotk large"></i>''+lg+'' large</span>'';');
    DBMS_OUTPUT.PUT_LINE('    if(md)h+=''<span><i class="dotk moderate"></i>''+md+'' moderate</span>'';');
    DBMS_OUTPUT.PUT_LINE('    if(nr)h+=''<span><i class="dotk typical"></i>''+nr+'' normal</span>'';');
    DBMS_OUTPUT.PUT_LINE('  }else if(kind===''sql''){');
    DBMS_OUTPUT.PUT_LINE('    var pc=$$(''.r:not(.sub) .glf.gp'',lane).length,nw=$$(''.glf.gn'',lane).length,dp=$$(''.glf.gd'',lane).length;');
    DBMS_OUTPUT.PUT_LINE('    if(pc)h+=''<span><b>\u25c6</b> ''+pc+'' plan change''+(pc>1?''s'':'''')+''</span>'';');
    DBMS_OUTPUT.PUT_LINE('    if(nw)h+=''<span><b>\u271a</b> ''+nw+'' new</span>'';');
    DBMS_OUTPUT.PUT_LINE('    if(dp)h+=''<span><b>\u25bd</b> ''+dp+'' DOP</span>'';');
    DBMS_OUTPUT.PUT_LINE('    if(!h)h=''<span class="muted">ranked, not scored</span>'';');
    DBMS_OUTPUT.PUT_LINE('  }else if(kind===''config''){');
    DBMS_OUTPUT.PUT_LINE('    var n=0,f=0;');
    DBMS_OUTPUT.PUT_LINE('    rows.forEach(function(r){if(!r.classList.contains(''p''))return;n++;var hit=false;$$(''.c'',r).forEach(function(c){if($(''.nd'',c)&&W.markerAt&&W.markerAt(+c.getAttribute(''data-w'')))hit=true;});if(hit)f++;});');
    DBMS_OUTPUT.PUT_LINE('    h=''<span class="muted">''+(f&&f===n?(n>1?''all ''+n+'' under a flag'':''under a flag''):f?f+'' of ''+n+'' under a flag'':n+'' changed'')+''</span>'';');
    DBMS_OUTPUT.PUT_LINE('  }else h=''<span class="muted">''+esc(lane.getAttribute(''data-note'')||''not scored'')+''</span>'';');
    DBMS_OUTPUT.PUT_LINE('  m.innerHTML=h;');
    DBMS_OUTPUT.PUT_LINE('  return [lg,md];');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('function lanes(){');
    DBMS_OUTPUT.PUT_LINE('  var tl=doc.getElementById(''tl'');if(!tl)return;');
    DBMS_OUTPUT.PUT_LINE('  var np=wins().length,tot=[0,0];');
    DBMS_OUTPUT.PUT_LINE('  $$(''.lane'',tl).forEach(function(lane){');
    DBMS_OUTPUT.PUT_LINE('    var more=$$(''.lrows > .r.more'',lane);');
    DBMS_OUTPUT.PUT_LINE('    if(more.length&&!$(''.r.xpr'',lane)){');
    DBMS_OUTPUT.PUT_LINE('      var x=doc.createElement(''div'');x.className=''r xpr'';x.setAttribute(''role'',''row'');');
    DBMS_OUTPUT.PUT_LINE('      var h=''<div class="l" role="rowheader"><button class="xpb" type="button" aria-expanded="false">+ Show ''+more.length+'' more ''+esc(lane.getAttribute(''data-noun'')||''rows'')+''</button></div>'';');
    DBMS_OUTPUT.PUT_LINE('      wins().forEach(function(w){h+=''<div class="c''+(w.o===0?'' cur'':'''')+''" data-w="''+w.o+''"></div>'';});');
    DBMS_OUTPUT.PUT_LINE('      x.innerHTML=h+''<div class="g" role="cell"></div>'';');
    DBMS_OUTPUT.PUT_LINE('      more[0].parentNode.insertBefore(x,more[0]);');
    DBMS_OUTPUT.PUT_LINE('      $(''.xpb'',x).addEventListener(''click'',function(){showMore(lane);});');
    DBMS_OUTPUT.PUT_LINE('    }');
    DBMS_OUTPUT.PUT_LINE('    var n=laneMeta(lane);tot[0]+=n[0];tot[1]+=n[1];');
    DBMS_OUTPUT.PUT_LINE('    var b=$(''.lt2'',lane);');
    DBMS_OUTPUT.PUT_LINE('    if(b)b.addEventListener(''click'',function(){var open=lane.classList.toggle(''closed'')===false;b.setAttribute(''aria-expanded'',String(open));if(open&&W.render)W.render(lane);});');
    DBMS_OUTPUT.PUT_LINE('    var rl=doc.querySelector(''nav.toc a[href="#''+lane.id+''"]'');');
    DBMS_OUTPUT.PUT_LINE('    if(rl){rl.hidden=lane.hidden;if(n[0]){var p=mk(''span'',''cnt c'',rl);p.textContent=n[0];}if(n[1]){var q=mk(''span'',''cnt w'',rl);q.textContent=n[1];}}');
    DBMS_OUTPUT.PUT_LINE('    var jn=$(''.jumpnav a[href="#''+lane.id+''"]'',tl);if(jn)jn.hidden=lane.hidden;');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('  var h2=$(''#timeline > h2'');');
    DBMS_OUTPUT.PUT_LINE('  if(h2&&!$(''.meta'',h2)&&(tot[0]||tot[1])){var m=mk(''span'',''meta'');m.innerHTML=(tot[0]?''<span><i class="dotk large"></i>''+tot[0]+'' large</span>'':'''')+(tot[1]?''<span><i class="dotk moderate"></i>''+tot[1]+'' moderate</span>'':'''');h2.appendChild(m);}');
    DBMS_OUTPUT.PUT_LINE('  if(!np)return;');
    DBMS_OUTPUT.PUT_LINE('  /* a skipped window (no valid snapshot pair) greys its date in the ruler */');
    DBMS_OUTPUT.PUT_LINE('  wins().forEach(function(w){if(w.v!==''N'')return;var h=$(''.ruler .h[data-w="''+w.o+''"]'',tl);if(h){h.classList.add(''skw'');h.title+='' (skipped window: left out of every baseline)'';}});');
    DBMS_OUTPUT.PUT_LINE('  /* the prior values, filled from data-v (shown on hover / pin) */');
    DBMS_OUTPUT.PUT_LINE('  $$(''.r.bars[data-v]'',tl).forEach(function(row){');
    DBMS_OUTPUT.PUT_LINE('    var v=nums(row.getAttribute(''data-v''));');
    DBMS_OUTPUT.PUT_LINE('    $$('':scope > .c[data-w]'',row).forEach(function(c){');
    DBMS_OUTPUT.PUT_LINE('      if($(''.v'',c))return;var x=v[idxOf(c.getAttribute(''data-w''))];');
    DBMS_OUTPUT.PUT_LINE('      c.insertAdjacentHTML(''afterbegin'',x==null?''<span class="v nil" aria-label="no value">\u2013</span>'':''<span class="v">''+fmtNum(x)+''</span>'');');
    DBMS_OUTPUT.PUT_LINE('    });');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('/* ---- 3. pin a window: its column tints, the gutter compares against it */');
    DBMS_OUTPUT.PUT_LINE('var PW=null;');
    DBMS_OUTPUT.PUT_LINE('W.pinned=function(){return PW;};');
    DBMS_OUTPUT.PUT_LINE('function flashCol(o){');
    DBMS_OUTPUT.PUT_LINE('  $$(''#tl .c[data-w="''+o+''"], #tl .ruler .h[data-w="''+o+''"]'').forEach(function(c){c.classList.remove(''colflash'');void c.offsetWidth;c.classList.add(''colflash'');});');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('W.pin=function(o){');
    DBMS_OUTPUT.PUT_LINE('  var tl=doc.getElementById(''tl'');if(!tl)return;');
    DBMS_OUTPUT.PUT_LINE('  o=(o==null||o==='''')?null:+o;');
    DBMS_OUTPUT.PUT_LINE('  var same=(PW!==null&&o===PW),bd=doc.body,gt=doc.getElementById(''tl-gt''),gs=doc.getElementById(''tl-gs'');');
    DBMS_OUTPUT.PUT_LINE('  $$(''.ruler .h[aria-pressed]'',tl).forEach(function(h){h.setAttribute(''aria-pressed'',''false'');});');
    DBMS_OUTPUT.PUT_LINE('  $$(''.pc'',tl).forEach(function(x){x.classList.remove(''pc'');});');
    DBMS_OUTPUT.PUT_LINE('  $$(''.r .g .d1[data-orig]'',tl).forEach(function(d){d.innerHTML=d.getAttribute(''data-orig'');d.removeAttribute(''data-orig'');});');
    DBMS_OUTPUT.PUT_LINE('  if(same||o===null||o===0){');
    DBMS_OUTPUT.PUT_LINE('    PW=null;bd.removeAttribute(''data-pw'');');
    DBMS_OUTPUT.PUT_LINE('    if(gt)gt.textContent=''vs prior mean'';if(gs)gs.textContent=''click a date to pin'';');
    DBMS_OUTPUT.PUT_LINE('    drawAll(true);return;');
    DBMS_OUTPUT.PUT_LINE('  }');
    DBMS_OUTPUT.PUT_LINE('  var w=winAt(o),i=idxOf(o);if(!w)return;');
    DBMS_OUTPUT.PUT_LINE('  PW=o;bd.setAttribute(''data-pw'',String(o));');
    DBMS_OUTPUT.PUT_LINE('  var h=$(''.ruler .h[data-w="''+o+''"]'',tl);if(h)h.setAttribute(''aria-pressed'',''true'');');
    DBMS_OUTPUT.PUT_LINE('  $$(''[data-w="''+o+''"]'',tl).forEach(function(x){if(!x.closest(''.flags''))x.classList.add(''pc'');});');
    DBMS_OUTPUT.PUT_LINE('  $$(''.r.bars[data-v]'',tl).forEach(function(row){');
    DBMS_OUTPUT.PUT_LINE('    var d=$('':scope > .g .d1'',row);if(!d)return;');
    DBMS_OUTPUT.PUT_LINE('    var v=nums(row.getAttribute(''data-v''));');
    DBMS_OUTPUT.PUT_LINE('    d.setAttribute(''data-orig'',d.innerHTML);');
    DBMS_OUTPUT.PUT_LINE('    d.textContent=delta(v[v.length-1],v[i])+'' vs ''+w.d;');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('  if(gt){gt.innerHTML=''vs ''+esc(w.d)+'' <button type="button" class="unpin" aria-label="Clear the pinned window">clear</button>'';$(''.unpin'',gt).addEventListener(''click'',function(){W.pin(null);});}');
    DBMS_OUTPUT.PUT_LINE('  if(gs)gs.textContent=''band stays vs prior mean'';');
    DBMS_OUTPUT.PUT_LINE('  drawAll(true);');
    DBMS_OUTPUT.PUT_LINE('};');
    DBMS_OUTPUT.PUT_LINE('doc.addEventListener(''click'',function(ev){');
    DBMS_OUTPUT.PUT_LINE('  var h=ev.target&&ev.target.closest?ev.target.closest(''#tl .ruler .h[data-w]''):null;if(!h)return;');
    DBMS_OUTPUT.PUT_LINE('  var o=+h.getAttribute(''data-w'');');
    DBMS_OUTPUT.PUT_LINE('  if(o===0){W.pin(null);flashCol(0);}else W.pin(o);');
    DBMS_OUTPUT.PUT_LINE('});');
    DBMS_OUTPUT.PUT_LINE('/* Esc: the first press clears a highlighted Activity series (hlEsc,');
    DBMS_OUTPUT.PUT_LINE('   section 6), the next one the pinned window */');
    DBMS_OUTPUT.PUT_LINE('doc.addEventListener(''keydown'',function(ev){if(ev.key!==''Escape'')return;if(hlEsc())return;if(PW!==null)W.pin(null);});');
    DBMS_OUTPUT.PUT_LINE('/* the pin survives a view switch: the Activity charts that show it are at');
    DBMS_OUTPUT.PUT_LINE('   the top of every view (Esc, Current or the gutter''s clear unpin) */');
    DBMS_OUTPUT.PUT_LINE('doc.addEventListener(''awr:view'',function(ev){');
    DBMS_OUTPUT.PUT_LINE('  var v=ev.detail&&ev.detail.view;');
    DBMS_OUTPUT.PUT_LINE('  setTimeout(function(){drawAll(true);if(v===''timeline''){sync();startAtCurrent();}},50);');
    DBMS_OUTPUT.PUT_LINE('});');
    DBMS_OUTPUT.PUT_LINE('/* ---- 4. tooltip over the grid and the full-span chart */');
    DBMS_OUTPUT.PUT_LINE('var tip=null;');
    DBMS_OUTPUT.PUT_LINE('function tipOn(html,e){if(!tip)return;tip.innerHTML=html;tip.hidden=false;place(e);}');
    DBMS_OUTPUT.PUT_LINE('function tipOff(){if(tip)tip.hidden=true;}');
    DBMS_OUTPUT.PUT_LINE('function place(e){');
    DBMS_OUTPUT.PUT_LINE('  var x=e.clientX+14,y=e.clientY+16,w=tip.offsetWidth,h=tip.offsetHeight;');
    DBMS_OUTPUT.PUT_LINE('  if(x+w>innerWidth-8)x=e.clientX-w-12;if(y+h>innerHeight-8)y=e.clientY-h-12;');
    DBMS_OUTPUT.PUT_LINE('  tip.style.left=Math.max(8,x)+''px'';tip.style.top=Math.max(8,y)+''px'';');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('/* per-series AAS rows, top of the stack first; names / colours from the');
    DBMS_OUTPUT.PUT_LINE('   payload (classes or events), vis = the legend state (null = all) */');
    DBMS_OUTPUT.PUT_LINE('function ashRows(names,cols,get,vis,noun,hl){');
    DBMS_OUTPUT.PUT_LINE('  var h='''',tot=0,hid=false,lead=[],hs=0;');
    DBMS_OUTPUT.PUT_LINE('  for(var c=names.length-1;c>=0;c--){if(vis&&!vis[c]){hid=true;continue;}var v=get(c);if(v==null)continue;tot+=v;');
    DBMS_OUTPUT.PUT_LINE('    if(hl&&hl[c]){lead.push([c,v]);hs+=v;continue;}');
    DBMS_OUTPUT.PUT_LINE('    if(v>=0.005)h+=''<div class="tr2"><span><i class="sw" style="--sw:''+cols[c]+''"></i>''+esc(names[c])+''</span><b>''+v.toFixed(2)+''</b></div>'';}');
    DBMS_OUTPUT.PUT_LINE('  /* a highlighted series leads (its share of the total beside it); several');
    DBMS_OUTPUT.PUT_LINE('     (a wait class''s events) add their sum */');
    DBMS_OUTPUT.PUT_LINE('  var pc=function(v){return tot>0?'' <span class="tpc">''+Math.round(v/tot*100)+''%</span>'':'''';},l='''';');
    DBMS_OUTPUT.PUT_LINE('  lead.forEach(function(x){l+=''<div class="tr2 thl"><span><i class="sw" style="--sw:''+cols[x[0]]+''"></i>''+esc(names[x[0]])+''</span><b>''+x[1].toFixed(2)+pc(x[1])+''</b></div>'';});');
    DBMS_OUTPUT.PUT_LINE('  if(lead.length>1)l+=''<div class="tr2 thl"><span>Highlighted, together</span><b>''+hs.toFixed(2)+pc(hs)+''</b></div>'';');
    DBMS_OUTPUT.PUT_LINE('  return (l?''<div class="thlb">''+l+''</div>'':'''')+h+''<div class="tr2 tsum"><span>''+(hid?''Total, shown ''+(noun||''classes''):''Total'')+''</span><b>''+tot.toFixed(1)+'' AAS</b></div>'';');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('function cellTip(cell){');
    DBMS_OUTPUT.PUT_LINE('  var row=cell.closest(''.r'');if(!row||!row.getAttribute(''data-name''))return '''';');
    DBMS_OUTPUT.PUT_LINE('  var o=+cell.getAttribute(''data-w''),w=winAt(o),i=idxOf(o);if(!w)return '''';');
    DBMS_OUTPUT.PUT_LINE('  var head=''<b>''+esc(row.getAttribute(''data-name''))+''</b><br><span class="tm">''+esc(w.t)+'', ''+offTxt(w)+(w.v===''N''?'', skipped window'':'''')+''</span><br>'';');
    DBMS_OUTPUT.PUT_LINE('  if(row.classList.contains(''ash'')&&AX&&AX.win)return head+ashRows(AX.classes,AX.classes.map(wcol),function(c){return AX.win[c][i];});');
    DBMS_OUTPUT.PUT_LINE('  if(row.classList.contains(''p''))return head+''<b>''+esc(cell.getAttribute(''data-pv'')||'''')+''</b>'';');
    DBMS_OUTPUT.PUT_LINE('  var v=nums(row.getAttribute(''data-v''))[i];');
    DBMS_OUTPUT.PUT_LINE('  if(v==null)return head+''<span class="tm">''+(row.classList.contains(''q'')||row.classList.contains(''o'')?''not in the top list in this window'':''no value in this window'')+''</span>'';');
    DBMS_OUTPUT.PUT_LINE('  var g=$(''.glf'',cell);');
    DBMS_OUTPUT.PUT_LINE('  return head+''<b>''+fmtNum(v)+''</b> ''+esc(row.getAttribute(''data-unit'')||'''')+(g?''<br>''+esc(g.title):'''');');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('doc.addEventListener(''mouseover'',function(e){');
    DBMS_OUTPUT.PUT_LINE('  var t=e.target;if(!t||!t.closest||!tip)return;');
    DBMS_OUTPUT.PUT_LINE('  if(t.closest(''.ashx .axp''))return;');
    DBMS_OUTPUT.PUT_LINE('  var c=t.closest(''#tl .lrows .c[data-w]'');');
    DBMS_OUTPUT.PUT_LINE('  if(c){var s=cellTip(c);if(s){tipOn(s,e);return;}}');
    DBMS_OUTPUT.PUT_LINE('  tipOff();');
    DBMS_OUTPUT.PUT_LINE('});');
    DBMS_OUTPUT.PUT_LINE('doc.addEventListener(''mousemove'',function(e){if(tip&&!tip.hidden&&!(e.target.closest&&e.target.closest(''.ashx .axp'')))place(e);},{passive:true});');
    DBMS_OUTPUT.PUT_LINE('doc.addEventListener(''scroll'',tipOff,{passive:true});');
    DBMS_OUTPUT.PUT_LINE('/* ---- 5. stacked activity per window: the Activity lane and the DB time card */');
    DBMS_OUTPUT.PUT_LINE('function stack(row,vals,opt){');
    DBMS_OUTPUT.PUT_LINE('  var A=AX,np=wins().length,tot=[],mx=0;');
    DBMS_OUTPUT.PUT_LINE('  for(var i=0;i<np;i++){var s=0;A.classes.forEach(function(c,k){s+=vals[k][i]||0;});tot.push(s);if(s>mx)mx=s;}');
    DBMS_OUTPUT.PUT_LINE('  if(!(mx>0))return false;');
    DBMS_OUTPUT.PUT_LINE('  var step=niceStep(mx,3),max=mx*1.04,ticks=[];for(var t=step;t<=max+1e-9;t+=step)ticks.push(t);');
    DBMS_OUTPUT.PUT_LINE('  var bh=cssNum(row,''--bh'',148),bb=cssNum(row,''--bb'',6),GAP=2;');
    DBMS_OUTPUT.PUT_LINE('  $$('':scope > .c[data-w]'',row).forEach(function(c){');
    DBMS_OUTPUT.PUT_LINE('    var i=idxOf(c.getAttribute(''data-w''));if(i<0)return;');
    DBMS_OUTPUT.PUT_LINE('    $$(''.stk,.gline,.dl'',c).forEach(function(x){x.parentNode.removeChild(x);});');
    DBMS_OUTPUT.PUT_LINE('    ticks.forEach(function(t){var g=mk(''i'',''gline'',c);g.style.bottom=(bb+t/max*bh)+''px'';});');
    DBMS_OUTPUT.PUT_LINE('    var st=mk(''div'',''stk'',c),y=0,segs=[];');
    DBMS_OUTPUT.PUT_LINE('    A.classes.forEach(function(name,k){');
    DBMS_OUTPUT.PUT_LINE('      var v=vals[k][i]||0,h=v/max*bh;if(h<0.4)return;');
    DBMS_OUTPUT.PUT_LINE('      var s=mk(''i'','''',st);s.style.background=wcol(name);s.style.bottom=y+''px'';s.style.height=Math.max(0.6,h-(h>4?GAP:0))+''px'';');
    DBMS_OUTPUT.PUT_LINE('      segs.push({n:name,v:v,mid:y+h/2});y+=h;');
    DBMS_OUTPUT.PUT_LINE('    });');
    DBMS_OUTPUT.PUT_LINE('    if(c.classList.contains(''cur'')&&opt.labels){');
    DBMS_OUTPUT.PUT_LINE('      var last=-99;');
    DBMS_OUTPUT.PUT_LINE('      segs.slice().sort(function(a,b){return b.v-a.v;}).slice(0,2).sort(function(a,b){return a.mid-b.mid;}).forEach(function(s){');
    DBMS_OUTPUT.PUT_LINE('        if(s.v/max*bh<8)return;');
    DBMS_OUTPUT.PUT_LINE('        var pos=Math.max(s.mid,last+16);last=pos;');
    DBMS_OUTPUT.PUT_LINE('        var d=mk(''span'',''dl'',c);d.innerHTML=''<i class="sw" style="--sw:''+wcol(s.n)+''"></i>''+aasTxt(s.v);d.title=s.n;d.style.bottom=(bb+pos)+''px'';');
    DBMS_OUTPUT.PUT_LINE('      });');
    DBMS_OUTPUT.PUT_LINE('    }');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('  var ax=$(''.axn'',row);');
    DBMS_OUTPUT.PUT_LINE('  if(ax){ax.innerHTML='''';[0].concat(ticks).forEach(function(t){var i=mk(''i'','''',ax);i.textContent=t;i.style.bottom=(bb+t/max*bh)+''px'';});}');
    DBMS_OUTPUT.PUT_LINE('  return true;');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('function activity(){');
    DBMS_OUTPUT.PUT_LINE('  if(!AX||!AX.win||!AX.classes.length)return;');
    DBMS_OUTPUT.PUT_LINE('  $$(''#tl .r.ash'').forEach(function(row){stack(row,AX.win,{labels:true});});');
    DBMS_OUTPUT.PUT_LINE('  /* the DB time card: FOREGROUND ASH per window, stacked by wait class.');
    DBMS_OUTPUT.PUT_LINE('     DB time is foreground time and ASH''s foreground samples are its');
    DBMS_OUTPUT.PUT_LINE('     sampled estimate, so the bars measure what the headline measures;');
    DBMS_OUTPUT.PUT_LINE('     the Current value printed stays the card''s DB time. */');
    DBMS_OUTPUT.PUT_LINE('  var row=$(''#f-dbtime .fc-main .wg .r.bars'');if(!row)return;');
    DBMS_OUTPUT.PUT_LINE('  var W=AX.winfg||AX.win,np=wins().length,cur=[];');
    DBMS_OUTPUT.PUT_LINE('  AX.classes.forEach(function(c,k){cur.push([c,W[k][np-1]||0,k]);});');
    DBMS_OUTPUT.PUT_LINE('  cur.sort(function(a,b){return b[1]-a[1];});');
    DBMS_OUTPUT.PUT_LINE('  row.classList.remove(''bars'');row.classList.add(''ash'');');
    DBMS_OUTPUT.PUT_LINE('  if(!stack(row,W,{labels:true})){row.classList.remove(''ash'');row.classList.add(''bars'');return;}');
    DBMS_OUTPUT.PUT_LINE('  var tot=0;cur.forEach(function(x){tot+=x[1];});');
    DBMS_OUTPUT.PUT_LINE('  $$('':scope > .c'',row).forEach(function(c){var v=$(''.v'',c);if(v&&!c.classList.contains(''cur''))v.parentNode.removeChild(v);});');
    DBMS_OUTPUT.PUT_LINE('  $$('':scope > .c > i'',row).forEach(function(x){x.parentNode.removeChild(x);});');
    DBMS_OUTPUT.PUT_LINE('  var ul=doc.createElement(''ul'');ul.className=''leg fcleg'';ul.setAttribute(''aria-label'',''Foreground active sessions by wait class, ASH'');');
    DBMS_OUTPUT.PUT_LINE('  ul.innerHTML=cur.filter(function(x){return x[1]>0;}).map(function(x){return ''<li><i class="sw" style="--sw:''+wcol(x[0])+''"></i>''+esc(x[0])+''</li>'';}).join('''');');
    DBMS_OUTPUT.PUT_LINE('  var wg=row.closest(''.wg'');wg.parentNode.insertBefore(ul,wg);');
    DBMS_OUTPUT.PUT_LINE('  wg.title=''Foreground active sessions (ASH, a sampled estimate of DB time) per compared window, stacked by wait class; Current ''+tot.toFixed(2)+'' AAS in ASH. The Current value is the DB time headline.'';');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('/* ---- 6. Activity, whole span (section#activity, top of every view): one');
    DBMS_OUTPUT.PUT_LINE('   chart factory, two instances over one time axis -- by wait class');
    DBMS_OUTPUT.PUT_LINE('   (AWR_DATA.ashx) and by wait event (AWR_DATA.ashe).  Linked: a zoom on');
    DBMS_OUTPUT.PUT_LINE('   either zooms both, the hover crosshair is mirrored, the pinned window');
    DBMS_OUTPUT.PUT_LINE('   (AWR_WG.pin) is the same stripe in both.  Hover, legend, brush zoom,');
    DBMS_OUTPUT.PUT_LINE('   Reset / double-click, window stripes, release markers in each.');
    DBMS_OUTPUT.PUT_LINE('   Series highlight: a legend entry hovered or keyboard-focused (or a');
    DBMS_OUTPUT.PUT_LINE('   sticky one) is drawn from zero with the y axis fitted to it, the other');
    DBMS_OUTPUT.PUT_LINE('   series faded on top; the series under the pointer in the plot is');
    DBMS_OUTPUT.PUT_LINE('   highlighted in place (no re-stacking, so it cannot slide away from the');
    DBMS_OUTPUT.PUT_LINE('   pointer).  Linked through ashe.ecls (each event''s wait class): a class');
    DBMS_OUTPUT.PUT_LINE('   highlights its events in the event chart, an event its class, lightly,');
    DBMS_OUTPUT.PUT_LINE('   in the class chart.  Sticky: a click on a band in the plot or');
    DBMS_OUTPUT.PUT_LINE('   Shift+click / Shift+Enter on a legend entry; the same again, a click');
    DBMS_OUTPUT.PUT_LINE('   off the stack or Esc clears it (the next Esc unpins the window). */');
    DBMS_OUTPUT.PUT_LINE('var AX=null,AE=null,CH=[],SP=null,DRAG=null,cvs=null;');
    DBMS_OUTPUT.PUT_LINE('/* the highlight: HS sticky, HT passing (legend hover / focus, or soft =');
    DBMS_OUTPUT.PUT_LINE('   the plot hover), each {c: chart, k: series}; HT wins while it lasts */');
    DBMS_OUTPUT.PUT_LINE('var HS=null,HT=null;');
    DBMS_OUTPUT.PUT_LINE('function hlSame(a,b){return a===b||!!(a&&b&&a.c===b.c&&a.k===b.k&&!!a.soft===!!b.soft);}');
    DBMS_OUTPUT.PUT_LINE('function hlSet(t){if(hlSame(HT,t))return;HT=t;hlApply();}');
    DBMS_OUTPUT.PUT_LINE('function hlStick(c,k){HS=(k<0||(HS&&HS.c===c&&HS.k===k))?null:{c:c,k:k};HT=null;hlApply();}');
    DBMS_OUTPUT.PUT_LINE('function hlEsc(){if(!HS&&!HT)return false;HS=null;HT=null;hlApply();return true;}');
    DBMS_OUTPUT.PUT_LINE('/* each chart''s c.hl = {set: {series: 1}, strong: re-based + fitted, fade:');
    DBMS_OUTPUT.PUT_LINE('   the others'' opacity, note}; redraw only the charts whose state changed */');
    DBMS_OUTPUT.PUT_LINE('function hlApply(){');
    DBMS_OUTPUT.PUT_LINE('  var E=HT||HS;');
    DBMS_OUTPUT.PUT_LINE('  CH.forEach(function(c){c.hl=null;});');
    DBMS_OUTPUT.PUT_LINE('  if(E&&E.c.vis[E.k]){');
    DBMS_OUTPUT.PUT_LINE('    var s=E.c,strong=!E.soft,nm=s.P.classes[E.k],one={},m=s.xmap&&s.xmap[E.k],o=s.peer;');
    DBMS_OUTPUT.PUT_LINE('    var tail=E===HS?'' \u00b7 Esc clears'':'''';');
    DBMS_OUTPUT.PUT_LINE('    one[E.k]=1;');
    DBMS_OUTPUT.PUT_LINE('    s.hl={set:one,strong:strong,fade:strong?0.12:0.3,note:strong?nm+'' drawn from zero, y axis fitted to it''+tail:''''};');
    DBMS_OUTPUT.PUT_LINE('    if(o&&m&&m.length){');
    DBMS_OUTPUT.PUT_LINE('      var set={};m.forEach(function(q){set[q]=1;});');
    DBMS_OUTPUT.PUT_LINE('      var on1=m.length===1&&o.P.classes[m[0]]===nm;');
    DBMS_OUTPUT.PUT_LINE('      o.hl=s===CH[0]?{set:set,strong:strong,fade:strong?0.12:0.3,note:strong?(on1?nm+'' drawn from zero, y axis fitted to it'':''The ''+nm+'' events drawn from zero, y axis fitted to them'')+tail:''''}');
    DBMS_OUTPUT.PUT_LINE('                    :{set:set,strong:false,fade:0.35,note:''''};');
    DBMS_OUTPUT.PUT_LINE('    }');
    DBMS_OUTPUT.PUT_LINE('  }');
    DBMS_OUTPUT.PUT_LINE('  CH.forEach(function(c){');
    DBMS_OUTPUT.PUT_LINE('    var h=c.hl,key=h?Object.keys(h.set).join('','')+''|''+h.strong+''|''+h.fade+''|''+h.note:'''';');
    DBMS_OUTPUT.PUT_LINE('    if(c.lg){c.lg.classList.toggle(''hlon'',!!h);$$(''.axc'',c.lg).forEach(function(b){b.classList.toggle(''hl'',!!(h&&h.set[+b.getAttribute(''data-c'')]));});}');
    DBMS_OUTPUT.PUT_LINE('    if(key!==c.hk){c.hk=key;draw(c,true);}');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('/* the series drawn under client point (x, y) on chart c, or -1 (off the');
    DBMS_OUTPUT.PUT_LINE('   stack): the bucket under x, its values stacked in the drawn order */');
    DBMS_OUTPUT.PUT_LINE('function seriesAt(c,x,y){');
    DBMS_OUTPUT.PUT_LINE('  if(!c.g||!c.g.ord)return -1;');
    DBMS_OUTPUT.PUT_LINE('  var r=c.svg.getBoundingClientRect(),sy=(y-r.top)*c.g.W/r.width;');
    DBMS_OUTPUT.PUT_LINE('  if(sy<c.g.top||sy>c.g.top+c.g.ph)return -1;');
    DBMS_OUTPUT.PUT_LINE('  var t=tAt(c,x);if(t<c.g.d0||t>c.g.d1)return -1;');
    DBMS_OUTPUT.PUT_LINE('  var ref=refAt(t);if(ref==null)return -1;');
    DBMS_OUTPUT.PUT_LINE('  var v=(c.g.top+c.g.ph-sy)/c.g.ph*c.g.ymax,acc=0;');
    DBMS_OUTPUT.PUT_LINE('  for(var q=0;q<c.g.ord.length;q++){var k=c.g.ord[q],a=rV(c,k,ref)||0;if(a<=0)continue;acc+=a;if(v<=acc)return k;}');
    DBMS_OUTPUT.PUT_LINE('  return -1;');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('/* the event palette: 15 categorical hues, the first 13 (all a chart can');
    DBMS_OUTPUT.PUT_LINE('   use: 14 events, CPU among them) well apart, readable on both themes, no');
    DBMS_OUTPUT.PUT_LINE('   green (CPU keeps the wait-class CPU green, "Other events" a fixed grey) */');
    DBMS_OUTPUT.PUT_LINE('var EVP=[''#4E79A7'',''#F28E2B'',''#E15759'',''#76B7B2'',''#EDC948'',''#B07AA1'',''#FF9DA7'',''#9C755F'',''#A0CBE8'',''#D37295'',''#17BECF'',''#B6992D'',''#7F3C8D'',''#FFBE7D'',''#499894''],EVO=''#9AA3AD'';');
    DBMS_OUTPUT.PUT_LINE('function evColors(names){var j=0;return names.map(function(n){if(n===''CPU'')return wcol(''CPU'');if(n===''Other events'')return EVO;return EVP[(j++)%EVP.length];});}');
    DBMS_OUTPUT.PUT_LINE('/* a bucket''s length as text: 15-min, 1-hour, 2-hour, 0.75 h = 45-min */');
    DBMS_OUTPUT.PUT_LINE('function bLab(h){return h<1&&Math.abs(h*60-Math.round(h*60))<1e-6?Math.round(h*60)+''-min'':(Math.round(h*100)/100)+''-hour'';}');
    DBMS_OUTPUT.PUT_LINE('/* the 1-minute detail (ashx.fine / ashe.fine): when the view is FMAX or');
    DBMS_OUTPUT.PUT_LINE('   narrower and overlaps a compared window, the minutes inside the windows');
    DBMS_OUTPUT.PUT_LINE('   replace the coarse buckets they overlap; zoomed that far the brush may');
    DBMS_OUTPUT.PUT_LINE('   go down to FMIN.  A bucket is a ref: coarse i >= 0, 1-minute j = -1 - j. */');
    DBMS_OUTPUT.PUT_LINE('var FMAX=6*H1,FMIN=30*6e4;');
    DBMS_OUTPUT.PUT_LINE('function rS(r){return r>=0?SP.T[r]:SP.F.T[-1-r];}');
    DBMS_OUTPUT.PUT_LINE('function rE(r){return r>=0?SP.T1[r]:Math.min(SP.F.T[-1-r]+SP.F.bm,SP.full[1]);}');
    DBMS_OUTPUT.PUT_LINE('function rV(c,k,r){return r>=0?c.P.vals[k][r]:c.FV[k][-1-r];}');
    DBMS_OUTPUT.PUT_LINE('/* a fine series: integer samples a minute, -k = k zero minutes; AAS = n / div */');
    DBMS_OUTPUT.PUT_LINE('function unRle(a,n,div){if(!a||!a.length)return null;var o=[],i,z,x;for(i=0;i<a.length;i++){x=+a[i];if(x<0){for(z=0;z<-x;z++)o.push(0);}else o.push(x/div);}return o.length===n?o:null;}');
    DBMS_OUTPUT.PUT_LINE('function fineInit(f){');
    DBMS_OUTPUT.PUT_LINE('  if(!f||!f.segs||!f.segs.length||!(f.bm>0))return null;');
    DBMS_OUTPUT.PUT_LINE('  var bm=f.bm*6e4,T=[],S=[];');
    DBMS_OUTPUT.PUT_LINE('  f.segs.forEach(function(g){var a=SP.t0+g[0]*6e4;S.push([a,a+g[1]*bm,T.length]);for(var q=0;q<g[1];q++)T.push(a+q*bm);});');
    DBMS_OUTPUT.PUT_LINE('  return {T:T,S:S,bm:bm,div:6*f.bm,capped:!!f.capped};');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('function fineVals(P){');
    DBMS_OUTPUT.PUT_LINE('  var f=P.fine,F=SP.F;if(!F||!f||!f.vals||f.vals.length!==P.classes.length)return null;');
    DBMS_OUTPUT.PUT_LINE('  var o=f.vals.map(function(a){return unRle(a,F.T.length,F.div);});');
    DBMS_OUTPUT.PUT_LINE('  return o.some(function(a){return !a;})?null:o;');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('/* the time the segments cover in [a, b) */');
    DBMS_OUTPUT.PUT_LINE('function fineCov(a,b){var F=SP.F,v=0;if(!F)return 0;F.S.forEach(function(g){var x=Math.max(a,g[0]),y=Math.min(b,g[1]);if(y>x)v+=y-x;});return v;}');
    DBMS_OUTPUT.PUT_LINE('function fineOn(a,b){return !!SP.F&&b-a<=FMAX+1&&fineCov(a,b)>0;}');
    DBMS_OUTPUT.PUT_LINE('/* the buckets drawn for [d0, d1], in time order, a bucket or two past each');
    DBMS_OUTPUT.PUT_LINE('   edge so the lines run out of the plot */');
    DBMS_OUTPUT.PUT_LINE('function refs(d0,d1){');
    DBMS_OUTPUT.PUT_LINE('  var key=d0+''|''+d1;if(SP.rk===key)return SP.rv;');
    DBMS_OUTPUT.PUT_LINE('  var br=bRange(d0,d1),n=SP.T.length,i0=Math.max(0,br[0]-1),i1=Math.min(n-1,br[1]+1),out=[],i;');
    DBMS_OUTPUT.PUT_LINE('  if(!fineOn(d0,d1)){for(i=i0;i<=i1;i++)out.push(i);}');
    DBMS_OUTPUT.PUT_LINE('  else{');
    DBMS_OUTPUT.PUT_LINE('    var F=SP.F,fl=[],cl=[],pa=d0-2*SP.bh,pb=d1+2*SP.bh;');
    DBMS_OUTPUT.PUT_LINE('    F.S.forEach(function(g){');
    DBMS_OUTPUT.PUT_LINE('      if(g[1]<=pa||g[0]>=pb)return;');
    DBMS_OUTPUT.PUT_LINE('      var nb=Math.round((g[1]-g[0])/F.bm),ja=Math.max(0,Math.floor((pa-g[0])/F.bm)),jb=Math.min(nb-1,Math.ceil((pb-g[0])/F.bm));');
    DBMS_OUTPUT.PUT_LINE('      for(var j=ja;j<=jb;j++)fl.push(-1-(g[2]+j));');
    DBMS_OUTPUT.PUT_LINE('    });');
    DBMS_OUTPUT.PUT_LINE('    for(i=i0;i<=i1;i++){var a=SP.T[i],b=SP.T1[i];if(!F.S.some(function(g){return g[0]<b&&g[1]>a;}))cl.push(i);}');
    DBMS_OUTPUT.PUT_LINE('    var p=0,q=0;while(p<cl.length||q<fl.length){if(q>=fl.length||(p<cl.length&&rS(cl[p])<rS(fl[q])))out.push(cl[p++]);else out.push(fl[q++]);}');
    DBMS_OUTPUT.PUT_LINE('  }');
    DBMS_OUTPUT.PUT_LINE('  SP.rk=key;SP.rv=out;return out;');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('/* the ref under time t (fine inside a window when the view shows the detail) */');
    DBMS_OUTPUT.PUT_LINE('function refAt(t){');
    DBMS_OUTPUT.PUT_LINE('  var F=SP.F;');
    DBMS_OUTPUT.PUT_LINE('  if(F&&fineOn(SP.dom[0],SP.dom[1]))for(var q=0;q<F.S.length;q++){var g=F.S[q];if(t>=g[0]&&t<g[1])return -1-(g[2]+Math.floor((t-g[0])/F.bm));}');
    DBMS_OUTPUT.PUT_LINE('  var j=bucketAt(t);return j<0?null:j;');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('/* a band''s top edge: the fill colour, darker */');
    DBMS_OUTPUT.PUT_LINE('function shade(h){var m=/^#([0-9a-f]{6})$/i.exec(h);if(!m)return h;var n=parseInt(m[1],16);return ''rgb(''+[n>>16,(n>>8)&255,n&255].map(function(v){return Math.round(v*0.8);}).join('','')+'')'';}');
    DBMS_OUTPUT.PUT_LINE('/* the buckets in [a, b): first and last index, O(1) on the regular grid */');
    DBMS_OUTPUT.PUT_LINE('function bRange(a,b){var n=SP.T.length,i0=Math.max(0,Math.floor((a-SP.t0)/SP.bh)),i1=Math.min(n-1,Math.ceil((b-SP.t0)/SP.bh)-1);');
    DBMS_OUTPUT.PUT_LINE('  while(i0<n&&SP.T1[i0]<=a)i0++;while(i1>=0&&SP.T[i1]>=b)i1--;return [i0,i1];}');
    DBMS_OUTPUT.PUT_LINE('function tw(t){if(!cvs)cvs=doc.createElement(''canvas'').getContext(''2d'');cvs.font=''11px ui-sans-serif, -apple-system, "Segoe UI", Inter, Roboto, system-ui, sans-serif'';return cvs.measureText(t).width;}');
    DBMS_OUTPUT.PUT_LINE('function okPay(P,n){return !!(P&&P.classes&&P.classes.length&&P.vals&&P.vals.length===P.classes.length&&P.vals[0]&&P.vals[0].length===n);}');
    DBMS_OUTPUT.PUT_LINE('function spInit(){');
    DBMS_OUTPUT.PUT_LINE('  var D=window.AWR_DATA||{};AX=D.ashx||null;AE=D.ashe||null;');
    DBMS_OUTPUT.PUT_LINE('  var panel=doc.getElementById(''ashx'');if(!panel)return;');
    DBMS_OUTPUT.PUT_LINE('  panel.hidden=false;');
    DBMS_OUTPUT.PUT_LINE('  var n=AX&&AX.vals&&AX.vals[0]?AX.vals[0].length:0;');
    DBMS_OUTPUT.PUT_LINE('  if(!AX||!AX.t0||!okPay(AX,n)){var e=$(''#ax-empty'',panel);if(e)e.hidden=false;$$(''.axch,.axn2,.axk'',panel).forEach(function(x){x.hidden=true;});return;}');
    DBMS_OUTPUT.PUT_LINE('  var bh=AX.bh*H1,t0=PT(AX.t0),end=PT(AX.end),T=[],T1=[];');
    DBMS_OUTPUT.PUT_LINE('  for(var i=0;i<n;i++){T.push(t0+i*bh);T1.push(Math.min(t0+(i+1)*bh,end));}');
    DBMS_OUTPUT.PUT_LINE('  SP={T:T,T1:T1,t0:t0,bh:bh,full:[t0,end],dom:[t0,end],win:wins().map(function(w){return [PT(w.s),PT(w.e)];}),');
    DBMS_OUTPUT.PUT_LINE('      min:Math.max(4*bh,Math.min(6*H1,(end-t0)/4)),bhTxt:AX.bh===1?''hourly'':bLab(AX.bh)+'' averages'',');
    DBMS_OUTPUT.PUT_LINE('      reset:doc.getElementById(''ax-reset''),range:doc.getElementById(''ax-range''),sel:null,F:null,rk:null,rv:null};');
    DBMS_OUTPUT.PUT_LINE('  SP.F=fineInit(AX.fine);');
    DBMS_OUTPUT.PUT_LINE('  CH=[];');
    DBMS_OUTPUT.PUT_LINE('  mkChart(doc.getElementById(''ax-cls''),AX,AX.classes.map(wcol),{flags:true,noun:''classes'',what:''wait class''});');
    DBMS_OUTPUT.PUT_LINE('  var ev=doc.getElementById(''ax-ev'');');
    DBMS_OUTPUT.PUT_LINE('  if(okPay(AE,n))mkChart(ev,AE,evColors(AE.classes),{noun:''events'',what:''wait event''});');
    DBMS_OUTPUT.PUT_LINE('  else if(ev)ev.hidden=true;');
    DBMS_OUTPUT.PUT_LINE('  /* the detail only when every chart has it */');
    DBMS_OUTPUT.PUT_LINE('  CH.forEach(function(c){c.FV=fineVals(c.P);});');
    DBMS_OUTPUT.PUT_LINE('  if(CH.some(function(c){return !c.FV;}))SP.F=null;');
    DBMS_OUTPUT.PUT_LINE('  if(CH.length)CH[CH.length-1].xl=true;');
    DBMS_OUTPUT.PUT_LINE('  /* the link between the charts: ashe.ecls[e] = event e''s wait class');
    DBMS_OUTPUT.PUT_LINE('     (CPU -> CPU, Other events -> null) */');
    DBMS_OUTPUT.PUT_LINE('  if(CH.length===2&&AE&&AE.ecls&&AE.ecls.length===AE.classes.length){');
    DBMS_OUTPUT.PUT_LINE('    var ca=CH[0],ce=CH[1];ca.peer=ce;ce.peer=ca;');
    DBMS_OUTPUT.PUT_LINE('    ca.xmap=AX.classes.map(function(cn){var o=[];AE.ecls.forEach(function(x,e){if(x===cn)o.push(e);});return o;});');
    DBMS_OUTPUT.PUT_LINE('    ce.xmap=AE.ecls.map(function(x){var i=x==null?-1:AX.classes.indexOf(x);return i<0?[]:[i];});');
    DBMS_OUTPUT.PUT_LINE('  }');
    DBMS_OUTPUT.PUT_LINE('  if(SP.reset)SP.reset.addEventListener(''click'',spReset);');
    DBMS_OUTPUT.PUT_LINE('  doc.addEventListener(''mousemove'',function(e){');
    DBMS_OUTPUT.PUT_LINE('    var dg=DRAG;if(!dg)return;');
    DBMS_OUTPUT.PUT_LINE('    if(!dg.moved&&Math.abs(e.clientX-dg.x0)<5)return;');
    DBMS_OUTPUT.PUT_LINE('    dg.moved=true;tipOff();hideAll();');
    DBMS_OUTPUT.PUT_LINE('    var c=dg.c,r=c.svg.getBoundingClientRect(),sc=r.width/c.g.W,mn=r.left+c.g.padL*sc,mx=r.left+(c.g.W-c.g.padR)*sc;');
    DBMS_OUTPUT.PUT_LINE('    dg.a=Math.max(mn,Math.min(dg.x0,e.clientX));dg.b=Math.min(mx,Math.max(dg.x0,e.clientX));');
    DBMS_OUTPUT.PUT_LINE('    /* the brush shows on both charts: same width, same x mapping */');
    DBMS_OUTPUT.PUT_LINE('    CH.forEach(function(o){if(!o.g)return;var ro=o.svg.getBoundingClientRect(),so=ro.width/o.g.W;');
    DBMS_OUTPUT.PUT_LINE('      o.br.hidden=false;o.br.style.left=(dg.a-ro.left)+''px'';o.br.style.width=Math.max(0,dg.b-dg.a)+''px'';');
    DBMS_OUTPUT.PUT_LINE('      o.br.style.top=(o.g.top*so)+''px'';o.br.style.height=(o.g.ph*so)+''px'';});');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('  doc.addEventListener(''mouseup'',function(){');
    DBMS_OUTPUT.PUT_LINE('    var dg=DRAG;if(!dg)return;DRAG=null;CH.forEach(function(o){o.br.hidden=true;});');
    DBMS_OUTPUT.PUT_LINE('    if(dg.moved){if(dg.b-dg.a>6)spZoom(tAt(dg.c,dg.a),tAt(dg.c,dg.b));return;}');
    DBMS_OUTPUT.PUT_LINE('    if(dg.w!=null){SP.sel={prev:PW,t:Date.now()};spSelect(dg.w);return;}');
    DBMS_OUTPUT.PUT_LINE('    /* a click on a band makes its highlight sticky (the same band again,');
    DBMS_OUTPUT.PUT_LINE('       or a click off the stack, clears it) */');
    DBMS_OUTPUT.PUT_LINE('    var k=seriesAt(dg.c,dg.x0,dg.y0);');
    DBMS_OUTPUT.PUT_LINE('    if(k>=0||HS){SP.hsel={prev:HS,t:Date.now()};hlStick(dg.c,k);}');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('function mkChart(root,P,cols,opt){');
    DBMS_OUTPUT.PUT_LINE('  if(!root)return null;');
    DBMS_OUTPUT.PUT_LINE('  var c={root:root,P:P,cols:cols,svg:$(''.axsvg'',root),plot:$(''.axp'',root),br:$(''.axbr'',root),');
    DBMS_OUTPUT.PUT_LINE('         vis:P.classes.map(function(){return true;}),flags:!!opt.flags,noun:opt.noun,what:opt.what,xl:false,g:null,w:0,uid:root.id,');
    DBMS_OUTPUT.PUT_LINE('         lg:$(''.axlg'',root),hl:null,hk:'''',peer:null,xmap:null};');
    DBMS_OUTPUT.PUT_LINE('  var lg=c.lg;');
    DBMS_OUTPUT.PUT_LINE('  if(lg){lg.innerHTML=P.classes.map(function(nm,k){return ''<button type="button" class="axc" data-c="''+k+''" aria-pressed="true" title="''+esc(nm)+'': hover to highlight, click to show or hide, Shift+click to keep it highlighted"><i class="sw" style="--sw:''+cols[k]+''" aria-hidden="true"></i>''+esc(nm)+''</button>'';}).join('''');');
    DBMS_OUTPUT.PUT_LINE('    /* hover / keyboard focus highlights; a click hides / shows; Shift+click');
    DBMS_OUTPUT.PUT_LINE('       or Shift+Enter keeps the highlight */');
    DBMS_OUTPUT.PUT_LINE('    $$(''.axc'',lg).forEach(function(b){');
    DBMS_OUTPUT.PUT_LINE('      var k=+b.getAttribute(''data-c''),mine=function(){return HT&&HT.c===c&&HT.k===k;};');
    DBMS_OUTPUT.PUT_LINE('      b.addEventListener(''click'',function(e){');
    DBMS_OUTPUT.PUT_LINE('        if(e.shiftKey){e.preventDefault();hlStick(c,k);return;}');
    DBMS_OUTPUT.PUT_LINE('        c.vis[k]=!c.vis[k];b.setAttribute(''aria-pressed'',String(c.vis[k]));hlApply();draw(c,true);});');
    DBMS_OUTPUT.PUT_LINE('      b.addEventListener(''keydown'',function(e){if(e.key===''Enter''&&e.shiftKey){e.preventDefault();hlStick(c,k);}});');
    DBMS_OUTPUT.PUT_LINE('      b.addEventListener(''mouseenter'',function(){hlSet({c:c,k:k});});');
    DBMS_OUTPUT.PUT_LINE('      b.addEventListener(''mouseleave'',function(){if(mine())hlSet(null);});');
    DBMS_OUTPUT.PUT_LINE('      b.addEventListener(''focus'',function(){var fv=true;try{fv=b.matches('':focus-visible'');}catch(x){}if(fv)hlSet({c:c,k:k});});');
    DBMS_OUTPUT.PUT_LINE('      b.addEventListener(''blur'',function(){if(mine())hlSet(null);});');
    DBMS_OUTPUT.PUT_LINE('    });}');
    DBMS_OUTPUT.PUT_LINE('  var s=c.svg;');
    DBMS_OUTPUT.PUT_LINE('  s.addEventListener(''mousemove'',function(e){hover(c,e);});');
    DBMS_OUTPUT.PUT_LINE('  s.addEventListener(''mouseleave'',function(){if(!DRAG){tipOff();hideAll();if(HT&&HT.soft)hlSet(null);}});');
    DBMS_OUTPUT.PUT_LINE('  s.addEventListener(''mousedown'',function(e){');
    DBMS_OUTPUT.PUT_LINE('    if(e.button!==0||!c.g)return;e.preventDefault();');
    DBMS_OUTPUT.PUT_LINE('    /* the second press of a double-click resets the zoom (the chart is redrawn');
    DBMS_OUTPUT.PUT_LINE('       between the two presses, so a dblclick event may never fire) and undoes');
    DBMS_OUTPUT.PUT_LINE('       the pin the first press made on a window stripe */');
    DBMS_OUTPUT.PUT_LINE('    if(e.detail>=2){if(SP.sel&&Date.now()-SP.sel.t<700)W.pin(SP.sel.prev);SP.sel=null;');
    DBMS_OUTPUT.PUT_LINE('      if(SP.hsel&&Date.now()-SP.hsel.t<700){HS=SP.hsel.prev;HT=null;hlApply();}SP.hsel=null;');
    DBMS_OUTPUT.PUT_LINE('      DRAG=null;spReset();return;}');
    DBMS_OUTPUT.PUT_LINE('    var wh=e.target.closest(''.xwh'');DRAG={c:c,x0:e.clientX,y0:e.clientY,moved:false,w:wh?+wh.getAttribute(''data-i''):null};');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('  s.addEventListener(''dblclick'',spReset);');
    DBMS_OUTPUT.PUT_LINE('  s.addEventListener(''keydown'',function(e){var wh=e.target.closest&&e.target.closest(''.xwh'');if(wh&&(e.key===''Enter''||e.key==='' '')){e.preventDefault();spSelect(+wh.getAttribute(''data-i''));}});');
    DBMS_OUTPUT.PUT_LINE('  CH.push(c);');
    DBMS_OUTPUT.PUT_LINE('  return c;');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('function drawAll(force){CH.forEach(function(c){draw(c,force);});spHead();}');
    DBMS_OUTPUT.PUT_LINE('function spHead(){');
    DBMS_OUTPUT.PUT_LINE('  if(!SP)return;var d0=SP.dom[0],d1=SP.dom[1],zoomed=d0>SP.full[0]||d1<SP.full[1];');
    DBMS_OUTPUT.PUT_LINE('  if(SP.reset)SP.reset.hidden=!zoomed;');
    DBMS_OUTPUT.PUT_LINE('  var res=SP.bhTxt;');
    DBMS_OUTPUT.PUT_LINE('  if(fineOn(d0,d1))res=fineCov(d0,d1)>=d1-d0-1?''1-min detail'':''1-min detail in the compared windows, ''+SP.bhTxt+'' elsewhere'';');
    DBMS_OUTPUT.PUT_LINE('  if(SP.range)SP.range.textContent=zoomed?fAt(d0)+'' to ''+fAt(d1)+'', zoomed, ''+res:fDay(SP.full[0])+'' to ''+fDay(SP.full[1])+'', ''+SP.bhTxt;');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('function draw(c,force){');
    DBMS_OUTPUT.PUT_LINE('  if(!c||!SP||!shown(c.plot))return;');
    DBMS_OUTPUT.PUT_LINE('  var Wd=Math.max(480,c.plot.clientWidth),d0=SP.dom[0],d1=SP.dom[1];');
    DBMS_OUTPUT.PUT_LINE('  if(!force&&c.w===Wd&&c.g&&c.pw===PW&&c.g.d0===d0&&c.g.d1===d1&&c.g.hk===c.hk)return;c.w=Wd;c.pw=PW;');
    DBMS_OUTPUT.PUT_LINE('  var mks=W.markers?W.markers():[],P=c.P;');
    DBMS_OUTPUT.PUT_LINE('  var top=c.flags&&mks.length?46:22,ph=150,bot=c.xl?26:8,padL=40,padR=14,H=top+ph+bot,pw=Wd-padL-padR;');
    DBMS_OUTPUT.PUT_LINE('  c.svg.setAttribute(''viewBox'',''0 0 ''+Wd+'' ''+H);c.svg.setAttribute(''height'',H);');
    DBMS_OUTPUT.PUT_LINE('  var X=function(t){return padL+pw*(t-d0)/(d1-d0);};');
    DBMS_OUTPUT.PUT_LINE('  /* stacked areas: one point per bucket at its midpoint, straight lines');
    DBMS_OUTPUT.PUT_LINE('     between them.  While a bucket is at least a pixel wide every bucket is');
    DBMS_OUTPUT.PUT_LINE('     a point; zoomed out further, one point per pixel column at the');
    DBMS_OUTPUT.PUT_LINE('     column''s busiest bucket (largest stacked total), so a one-bucket spike');
    DBMS_OUTPUT.PUT_LINE('     still shows; the tooltip always reads the bucket under the cursor.');
    DBMS_OUTPUT.PUT_LINE('     The first / last bucket of the data runs flat out to its edge. */');
    DBMS_OUTPUT.PUT_LINE('  /* the highlight (hlApply): on[k] = series k highlighted and shown; re-based');
    DBMS_OUTPUT.PUT_LINE('     (strong) = the highlighted series stacked first, from zero, the y axis');
    DBMS_OUTPUT.PUT_LINE('     fitted to them and each pixel column keeping THEIR busiest bucket */');
    DBMS_OUTPUT.PUT_LINE('  var hl=c.hl,on=null,i,k,sm,sh,r;');
    DBMS_OUTPUT.PUT_LINE('  if(hl){on=P.classes.map(function(x,q){return !!hl.set[q]&&c.vis[q];});if(!on.some(Boolean)){hl=null;on=null;}}');
    DBMS_OUTPUT.PUT_LINE('  var reb=!!(hl&&hl.strong),ord=[];');
    DBMS_OUTPUT.PUT_LINE('  for(k=0;k<P.vals.length;k++)if(c.vis[k]&&(!reb||on[k]))ord.push(k);');
    DBMS_OUTPUT.PUT_LINE('  if(reb)for(k=0;k<P.vals.length;k++)if(c.vis[k]&&!on[k])ord.push(k);');
    DBMS_OUTPUT.PUT_LINE('  var R=refs(d0,d1),pts=[],cb=null,mx=0.05,mh=0;');
    DBMS_OUTPUT.PUT_LINE('  for(i=0;i<R.length;i++){r=R[i];sm=0;sh=0;for(k=0;k<P.vals.length;k++)if(c.vis[k]){var vk=rV(c,k,r)||0;sm+=vk;if(reb&&on[k])sh+=vk;}');
    DBMS_OUTPUT.PUT_LINE('    var ra=rS(r),rb=rE(r);if(rb>d0&&ra<d1){if(sm>mx)mx=sm;if(sh>mh)mh=sh;}');
    DBMS_OUTPUT.PUT_LINE('    var xm=X((ra+rb)/2),col=Math.floor(xm),g=pts[pts.length-1];');
    DBMS_OUTPUT.PUT_LINE('    if(g&&col===cb){if(reb?(sh>g[3]||(sh===g[3]&&sm>g[2])):sm>g[2]){g[0]=xm;g[1]=r;g[2]=sm;g[3]=sh;}}else{pts.push([xm,r,sm,sh]);cb=col;}}');
    DBMS_OUTPUT.PUT_LINE('  if(pts.length){var pf=pts[0],pl=pts[pts.length-1];');
    DBMS_OUTPUT.PUT_LINE('    if(rS(pf[1])>=d0)pts.unshift([X(rS(pf[1])),pf[1],pf[2],pf[3]]);');
    DBMS_OUTPUT.PUT_LINE('    if(rE(pl[1])<=d1)pts.push([X(rE(pl[1])),pl[1],pl[2],pl[3]]);}');
    DBMS_OUTPUT.PUT_LINE('  var yb=reb&&mh>0?Math.max(mh,0.05):mx,step=niceStep(yb,3),ymax=Math.ceil(yb/step-1e-9)*step;');
    DBMS_OUTPUT.PUT_LINE('  var Y=function(v){return top+ph-ph*v/ymax;},clip=''axclip-''+c.uid;');
    DBMS_OUTPUT.PUT_LINE('  var s=''<defs><clipPath id="''+clip+''"><rect x="''+padL+''" y="''+(top-6)+''" width="''+pw+''" height="''+(ph+6)+''"/></clipPath>''');
    DBMS_OUTPUT.PUT_LINE('    +(reb?''<clipPath id="''+clip+''f"><rect x="''+padL+''" y="''+top+''" width="''+pw+''" height="''+ph+''"/></clipPath>'':'''')+''</defs>'';');
    DBMS_OUTPUT.PUT_LINE('  for(var v=0;v<=ymax+1e-9;v+=step){var dec=step<1?(step<0.1?2:1):0;');
    DBMS_OUTPUT.PUT_LINE('    s+=''<line class="gl" x1="''+padL+''" x2="''+(Wd-padR)+''" y1="''+Y(v).toFixed(1)+''" y2="''+Y(v).toFixed(1)+''"/><text class="at" x="''+(padL-6)+''" y="''+(Y(v)+4).toFixed(1)+''" text-anchor="end">''+v.toFixed(dec)+''</text>'';}');
    DBMS_OUTPUT.PUT_LINE('  s+=''<text class="at" x="''+(padL-6)+''" y="''+(top-10)+''" text-anchor="end">AAS</text><g clip-path="url(#''+clip+'')">'';');
    DBMS_OUTPUT.PUT_LINE('  /* one fill per series, painted top of the stack first: each fills from');
    DBMS_OUTPUT.PUT_LINE('     the axis up to its own cumulative line and the series below paint over');
    DBMS_OUTPUT.PUT_LINE('     it (no seams); then each band''s top edge, a thin darker line.  A point');
    DBMS_OUTPUT.PUT_LINE('     in the middle of a flat run is left out of the path.  Highlighted: the');
    DBMS_OUTPUT.PUT_LINE('     other series paint the same way inside one faded group (the group''s');
    DBMS_OUTPUT.PUT_LINE('     opacity applies once, so their overlap does not darken), then each');
    DBMS_OUTPUT.PUT_LINE('     highlighted series as its own band (between its lower and upper line)');
    DBMS_OUTPUT.PUT_LINE('     at full colour with a clear top edge. */');
    DBMS_OUTPUT.PUT_LINE('  var lo=pts.map(function(){return 0;}),np=pts.length,y0=Y(0).toFixed(1),fills=[],edges=[],hf=[],he=[];');
    DBMS_OUTPUT.PUT_LINE('  var pl2=function(ys,rev){var o='''',j,q;for(q=0;q<np;q++){j=rev?np-1-q:q;if(q>0&&q<np-1&&ys[j]===ys[rev?j+1:j-1]&&ys[j]===ys[rev?j-1:j+1])continue;o+=(o?''L'':'''')+pts[j][0].toFixed(1)+'' ''+ys[j];}return o;};');
    DBMS_OUTPUT.PUT_LINE('  ord.forEach(function(k){');
    DBMS_OUTPUT.PUT_LINE('    if(!np)return;');
    DBMS_OUTPUT.PUT_LINE('    var hi=lo.map(function(l,j){return l+(rV(c,k,pts[j][1])||0);}),ys=hi.map(function(h){return Y(h).toFixed(1);}),ln=pl2(ys,false);');
    DBMS_OUTPUT.PUT_LINE('    if(on&&on[k]){');
    DBMS_OUTPUT.PUT_LINE('      hf.push(''<path class="xa xah" fill="''+c.cols[k]+''" d="M''+ln+''L''+pl2(lo.map(function(h){return Y(h).toFixed(1);}),true)+''Z"/>'');');
    DBMS_OUTPUT.PUT_LINE('      he.push(''<path class="xe xeh" stroke="''+shade(c.cols[k])+''" d="M''+ln+''"/>'');');
    DBMS_OUTPUT.PUT_LINE('    }else{');
    DBMS_OUTPUT.PUT_LINE('      fills.push(''<path class="xa" fill="''+c.cols[k]+''" d="M''+pts[0][0].toFixed(1)+'' ''+y0+''L''+ln+''L''+pts[np-1][0].toFixed(1)+'' ''+y0+''Z"/>'');');
    DBMS_OUTPUT.PUT_LINE('      edges.push(''<path class="xe" stroke="''+shade(c.cols[k])+''" d="M''+ln+''"/>'');');
    DBMS_OUTPUT.PUT_LINE('    }');
    DBMS_OUTPUT.PUT_LINE('    lo=hi;');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('  if(!hl)s+=fills.reverse().join('''')+edges.reverse().join('''');');
    DBMS_OUTPUT.PUT_LINE('  /* fitted below the stack''s top, the faded stack would fill the plot: fainter then */');
    DBMS_OUTPUT.PUT_LINE('  else s+=(reb?''<g clip-path="url(#''+clip+''f)">'':'''')+''<g class="xfd" opacity="''+(reb&&ymax<mx?Math.min(hl.fade,0.07):hl.fade)+''">''+fills.reverse().join('''')+''</g>''+hf.join('''')+he.join('''')+(reb?''</g>'':'''');');
    DBMS_OUTPUT.PUT_LINE('  s+=''<rect class="xbk" x="0" y="''+top+''" width="0" height="''+ph+''" visibility="hidden"/>'';');
    DBMS_OUTPUT.PUT_LINE('  var ws=wins(),hit=[],cur=ws.length-1;');
    DBMS_OUTPUT.PUT_LINE('  SP.win.forEach(function(r,i){');
    DBMS_OUTPUT.PUT_LINE('    var xa=X(r[0]),xb=X(r[1]);if(xb<padL-2||xa>Wd-padR+2)return;');
    DBMS_OUTPUT.PUT_LINE('    var w=Math.max(i===cur?4:3,xb-xa),x=(xa+xb)/2-w/2,cls=(i===cur?'' cur'':'''')+(ws[i].o===PW?'' on'':'''')+(ws[i].v===''N''?'' sk'':'''')+(w>40?'' wd'':'''');');
    DBMS_OUTPUT.PUT_LINE('    s+=''<rect class="xw''+cls+''" x="''+x.toFixed(1)+''" y="''+top+''" width="''+w.toFixed(1)+''" height="''+ph+''"/><rect class="xwc''+cls+''" x="''+x.toFixed(1)+''" y="''+(top-5)+''" width="''+w.toFixed(1)+''" height="4" rx="1"/>'';');
    DBMS_OUTPUT.PUT_LINE('    hit.push([i,x,w]);');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('  s+=''</g><line class="ax" x1="''+padL+''" x2="''+(Wd-padR)+''" y1="''+(top+ph)+''" y2="''+(top+ph)+''"/>'';');
    DBMS_OUTPUT.PUT_LINE('  /* x ticks: the smallest interval that leaves about 88 px per label, counted from');
    DBMS_OUTPUT.PUT_LINE('     midnight of the Current window''s day (weekly ticks land on its weekday);');
    DBMS_OUTPUT.PUT_LINE('     labels on the lower chart only -- one shared axis */');
    DBMS_OUTPUT.PUT_LINE('  var IVS=[5/60,10/60,0.25,0.5,1,2,3,6,12,24,48,168,336,672].map(function(h){return h*H1;}),iv=IVS[IVS.length-1];');
    DBMS_OUTPUT.PUT_LINE('  for(var q=0;q<IVS.length;q++){if(pw*IVS[q]/(d1-d0)>=88){iv=IVS[q];break;}}');
    DBMS_OUTPUT.PUT_LINE('  var org=Math.floor(SP.win[cur][0]/864e5)*864e5;');
    DBMS_OUTPUT.PUT_LINE('  for(var tt=org+Math.ceil((d0-org)/iv)*iv;tt<=d1;tt+=iv){');
    DBMS_OUTPUT.PUT_LINE('    var xt=X(tt);if(xt<padL+12||xt>Wd-padR-12)continue;');
    DBMS_OUTPUT.PUT_LINE('    s+=''<line class="ax" x1="''+xt.toFixed(1)+''" x2="''+xt.toFixed(1)+''" y1="''+(top+ph)+''" y2="''+(top+ph+4)+''"/>'';');
    DBMS_OUTPUT.PUT_LINE('    if(c.xl)s+=''<text class="at" x="''+xt.toFixed(1)+''" y="''+(top+ph+18)+''" text-anchor="middle">''+((iv>=24*H1||new Date(tt).getUTCHours()===0)?fDay(tt):fHM(tt))+''</text>'';');
    DBMS_OUTPUT.PUT_LINE('  }');
    DBMS_OUTPUT.PUT_LINE('  /* release markers: a line through the plot on both charts; the flags (two');
    DBMS_OUTPUT.PUT_LINE('     tiers) on the upper one */');
    DBMS_OUTPUT.PUT_LINE('  var tiers=[[],[]];');
    DBMS_OUTPUT.PUT_LINE('  mks.forEach(function(m){');
    DBMS_OUTPUT.PUT_LINE('    var x=X(PT(m.at));if(x<padL||x>Wd-padR)return;');
    DBMS_OUTPUT.PUT_LINE('    if(!c.flags){s+=''<line class="cfl" x1="''+x.toFixed(1)+''" x2="''+x.toFixed(1)+''" y1="''+top+''" y2="''+(top+ph)+''"><title>''+esc(m.l+'', ''+m.t)+''</title></line>'';return;}');
    DBMS_OUTPUT.PUT_LINE('    [m.l,m.s].some(function(lb){');
    DBMS_OUTPUT.PUT_LINE('      var w=tw(lb)+12,x0=x+w>Wd-padR?x-w:x,end=x0!==x;');
    DBMS_OUTPUT.PUT_LINE('      for(var L=0;L<2;L++){');
    DBMS_OUTPUT.PUT_LINE('        if(tiers[L].some(function(r){return x0<r[1]+6&&x0+w>r[0]-6;}))continue;');
    DBMS_OUTPUT.PUT_LINE('        tiers[L].push([x0,x0+w]);var y=2+L*19;');
    DBMS_OUTPUT.PUT_LINE('        s+=''<line class="cfl" x1="''+x.toFixed(1)+''" x2="''+x.toFixed(1)+''" y1="''+(y+16)+''" y2="''+(top+ph)+''"/><line class="cf" x1="''+x.toFixed(1)+''" x2="''+x.toFixed(1)+''" y1="''+y+''" y2="''+(y+16)+''"/>''');
    DBMS_OUTPUT.PUT_LINE('          +''<rect class="cfh" x="''+(end?x0:x+1).toFixed(1)+''" y="''+y+''" width="''+(w-1)+''" height="16" rx="2"/>''');
    DBMS_OUTPUT.PUT_LINE('          +''<text class="cft" x="''+(end?x-6:x+6).toFixed(1)+''" y="''+(y+12)+''" text-anchor="''+(end?''end'':''start'')+''"><title>''+esc(m.l+'', ''+m.t)+''</title>''+esc(lb)+''</text>'';');
    DBMS_OUTPUT.PUT_LINE('        return true;');
    DBMS_OUTPUT.PUT_LINE('      }');
    DBMS_OUTPUT.PUT_LINE('      return false;');
    DBMS_OUTPUT.PUT_LINE('    });');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('  if(hl&&hl.note)s+=''<text class="xhn" x="''+(padL+6)+''" y="''+(top+13)+''">''+esc(hl.note)+''</text>'';');
    DBMS_OUTPUT.PUT_LINE('  s+=''<line class="xch" x1="0" x2="0" y1="''+top+''" y2="''+(top+ph)+''" visibility="hidden"/>'';');
    DBMS_OUTPUT.PUT_LINE('  /* a stripe''s hit area: the whole stripe while it is narrow; zoomed into');
    DBMS_OUTPUT.PUT_LINE('     a window (a wide stripe) only its cap, so the plot under it hovers');
    DBMS_OUTPUT.PUT_LINE('     bucket by bucket and a drag there zooms */');
    DBMS_OUTPUT.PUT_LINE('  hit.forEach(function(q){');
    DBMS_OUTPUT.PUT_LINE('    var i=q[0],w=ws[i],hw=Math.max(12,q[2]),hx=q[1]+q[2]/2-hw/2,hh=q[2]>24?10:ph+6;');
    DBMS_OUTPUT.PUT_LINE('    s+=''<rect class="xwh" data-i="''+i+''" data-w="''+w.o+''" x="''+hx.toFixed(1)+''" y="''+(top-6)+''" width="''+hw.toFixed(1)+''" height="''+hh+''" tabindex="0" role="button" aria-label="''');
    DBMS_OUTPUT.PUT_LINE('      +esc((w.o===0?''Current window, '':offTxt(w)+'' window, '')+w.t+(w.o===0?'''':''. Pin it''))+''"/>'';');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('  c.svg.innerHTML=s;');
    DBMS_OUTPUT.PUT_LINE('  c.g={X:X,W:Wd,padL:padL,padR:padR,top:top,ph:ph,pw:pw,d0:d0,d1:d1,ymax:ymax,ord:ord,hk:c.hk};');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('function tAt(c,cx){var r=c.svg.getBoundingClientRect(),x=(cx-r.left)*c.g.W/r.width;return c.g.d0+(x-c.g.padL)/c.g.pw*(c.g.d1-c.g.d0);}');
    DBMS_OUTPUT.PUT_LINE('function bucketAt(t){var j=Math.floor((t-SP.t0)/SP.bh);return j>=0&&j<SP.T.length&&t<SP.T1[j]?j:-1;}');
    DBMS_OUTPUT.PUT_LINE('function hideCross(c){var hb=$(''.xbk'',c.svg),ch=$(''.xch'',c.svg);if(hb){hb.setAttribute(''visibility'',''hidden'');ch.setAttribute(''visibility'',''hidden'');}}');
    DBMS_OUTPUT.PUT_LINE('function hideAll(){CH.forEach(hideCross);}');
    DBMS_OUTPUT.PUT_LINE('/* the crosshair + bucket band at time t (bucket ref r) on chart c */');
    DBMS_OUTPUT.PUT_LINE('function cross(c,t,r){');
    DBMS_OUTPUT.PUT_LINE('  var hb=$(''.xbk'',c.svg),ch=$(''.xch'',c.svg);if(!c.g||!hb)return;');
    DBMS_OUTPUT.PUT_LINE('  var xa=Math.max(c.g.padL,c.g.X(rS(r))),xb=Math.min(c.g.W-c.g.padR,c.g.X(rE(r))),x=c.g.X(t);');
    DBMS_OUTPUT.PUT_LINE('  hb.setAttribute(''x'',xa.toFixed(1));hb.setAttribute(''width'',Math.max(1,xb-xa).toFixed(1));hb.setAttribute(''visibility'',''visible'');');
    DBMS_OUTPUT.PUT_LINE('  ch.setAttribute(''x1'',x.toFixed(1));ch.setAttribute(''x2'',x.toFixed(1));ch.setAttribute(''visibility'',''visible'');');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('function hover(c,e){');
    DBMS_OUTPUT.PUT_LINE('  if(!c.g||DRAG&&DRAG.moved)return;');
    DBMS_OUTPUT.PUT_LINE('  var wh=e.target.closest&&e.target.closest(''.xwh''),P=c.P;');
    DBMS_OUTPUT.PUT_LINE('  if(wh){');
    DBMS_OUTPUT.PUT_LINE('    var i=+wh.getAttribute(''data-i''),w=wins()[i];hideAll();');
    DBMS_OUTPUT.PUT_LINE('    if(HT&&HT.soft)hlSet(null);');
    DBMS_OUTPUT.PUT_LINE('    tipOn(''<b>''+esc(w.t)+''</b><br><span class="tm">''+(w.o===0?''Current window'':offTxt(w)+'' window'')+(w.v===''N''?'', skipped'':'''')+'', by ''+c.what+''</span>''');
    DBMS_OUTPUT.PUT_LINE('      +(P.win?ashRows(P.classes,c.cols,function(k){return P.win[k][i];},c.vis,c.noun,c.hl&&c.hl.set):'''')+(w.o===0?'''':''<span class="tm">Click to pin this window</span>''),e);');
    DBMS_OUTPUT.PUT_LINE('    return;');
    DBMS_OUTPUT.PUT_LINE('  }');
    DBMS_OUTPUT.PUT_LINE('  var t=tAt(c,e.clientX),r=refAt(t);');
    DBMS_OUTPUT.PUT_LINE('  if(r==null||t<c.g.d0||t>c.g.d1){hideAll();tipOff();if(HT&&HT.soft)hlSet(null);return;}');
    DBMS_OUTPUT.PUT_LINE('  /* the band under the pointer highlights in place (not while one is sticky) */');
    DBMS_OUTPUT.PUT_LINE('  if(!HS&&!DRAG){var hk=seriesAt(c,e.clientX,e.clientY);hlSet(hk<0?null:{c:c,k:hk,soft:true});}');
    DBMS_OUTPUT.PUT_LINE('  CH.forEach(function(o){cross(o,t,r);});');
    DBMS_OUTPUT.PUT_LINE('  tipOn(''<b>''+fAt(rS(r))+''\u2013''+fHM(rE(r))+''</b><br><span class="tm">''+(r<0?''1-min'':bLab((rE(r)-rS(r))/H1))+'' average, by ''+c.what+''</span>''');
    DBMS_OUTPUT.PUT_LINE('    +ashRows(P.classes,c.cols,function(q){return rV(c,q,r);},c.vis,c.noun,c.hl&&c.hl.set),e);');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('/* a window stripe: pin it (Current unpins); in the Timeline view the grid');
    DBMS_OUTPUT.PUT_LINE('   column flashes and comes into view */');
    DBMS_OUTPUT.PUT_LINE('function spSelect(i){');
    DBMS_OUTPUT.PUT_LINE('  var w=wins()[i];if(!w)return;');
    DBMS_OUTPUT.PUT_LINE('  if(w.o===0){if(PW!==null)W.pin(null);}else W.pin(w.o);');
    DBMS_OUTPUT.PUT_LINE('  flashCol(w.o);');
    DBMS_OUTPUT.PUT_LINE('  var tl=doc.getElementById(''tl'');if(!tl||!shown(tl))return;');
    DBMS_OUTPUT.PUT_LINE('  var r=tl.getBoundingClientRect();if(r.top>innerHeight-220)window.scrollBy({top:r.top-innerHeight+320,behavior:reduced()?''auto'':''smooth''});');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('function spZoom(a,b){');
    DBMS_OUTPUT.PUT_LINE('  a=Math.max(SP.full[0],a);b=Math.min(SP.full[1],b);');
    DBMS_OUTPUT.PUT_LINE('  var mn=SP.F&&fineCov(a,b)>0?Math.min(SP.min,FMIN):SP.min;');
    DBMS_OUTPUT.PUT_LINE('  if(b-a<mn){var m=(a+b)/2;a=Math.max(SP.full[0],m-mn/2);b=Math.min(SP.full[1],a+mn);a=Math.max(SP.full[0],b-mn);}');
    DBMS_OUTPUT.PUT_LINE('  SP.dom=[a,b];drawAll(true);');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('function spReset(){if(!SP)return;SP.dom=SP.full.slice();drawAll(true);}');
    DBMS_OUTPUT.PUT_LINE('/* ---- 7. the grid''s scroll: the sticky ruler follows the body, lane captions stay in view */');
    DBMS_OUTPUT.PUT_LINE('function sync(){var b=doc.getElementById(''tl-body''),i=doc.getElementById(''tl-in''),r=$(''#tl > .ruler'');if(!b||!i)return;if(r)r.scrollLeft=b.scrollLeft;i.style.setProperty(''--sl'',b.scrollLeft+''px'');i.style.setProperty(''--vw'',b.clientWidth+''px'');}');
    DBMS_OUTPUT.PUT_LINE('function startAtCurrent(){var b=doc.getElementById(''tl-body'');if(b&&b.scrollWidth>b.clientWidth+2&&!b.scrollLeft)b.scrollLeft=b.scrollWidth;sync();}');
    DBMS_OUTPUT.PUT_LINE('/* ---- boot */');
    DBMS_OUTPUT.PUT_LINE('doc.addEventListener(''DOMContentLoaded'',function(){');
    DBMS_OUTPUT.PUT_LINE('  tip=doc.getElementById(''tip'');if(!tip){tip=mk(''div'','''',doc.body);tip.id=''tip'';tip.setAttribute(''role'',''tooltip'');tip.hidden=true;}');
    DBMS_OUTPUT.PUT_LINE('  $$(''.sw[data-wc]'').forEach(function(s){s.style.setProperty(''--sw'',wcol(s.getAttribute(''data-wc'')));});');
    DBMS_OUTPUT.PUT_LINE('  AX=(window.AWR_DATA||{}).ashx||null;');
    DBMS_OUTPUT.PUT_LINE('  lanes();');
    DBMS_OUTPUT.PUT_LINE('  activity();');
    DBMS_OUTPUT.PUT_LINE('  spInit();');
    DBMS_OUTPUT.PUT_LINE('  var b=doc.getElementById(''tl-body'');if(b)b.addEventListener(''scroll'',sync,{passive:true});');
    DBMS_OUTPUT.PUT_LINE('  var tl=doc.getElementById(''tl'');if(tl&&W.render)W.render(tl);');
    DBMS_OUTPUT.PUT_LINE('  setTimeout(function(){drawAll(true);startAtCurrent();},60);');
    DBMS_OUTPUT.PUT_LINE('  var rt=null;window.addEventListener(''resize'',function(){if(rt)clearTimeout(rt);rt=setTimeout(function(){drawAll();sync();},120);});');
    DBMS_OUTPUT.PUT_LINE('});');
    DBMS_OUTPUT.PUT_LINE('})();');
    DBMS_OUTPUT.PUT_LINE('</script>');
END;
/
