--
-- sql/lib/js_timeline.plsql
--
-- Client half of the Timeline view (v1.6.0, Mock D): the aligned window
-- grid (#tl, skeleton emitted by sql/00_params.sql, rows by the sections
-- through sql/lib/timeline.plsql) and the full-span interactive ASH chart
-- (#tl-ash, payload window.AWR_DATA.ashx from sql/09_ash_timeline.sql).
-- Emitted once by the driver prologue, right after js_wingrid.plsql (it
-- extends window.AWR_WG); pure inline JS + SVG, CDN-free, so it works
-- offline and with ECharts blocked.  Colours come from CSS variables,
-- except the fixed wait-class palette (window.AWR_WAIT_COLORS,
-- sql/lib/js_wait_colors.plsql).
--
-- Exposes window.AWR_TL:
--   take()        called by the inline script after each section's
--                 <template class="tl-src" data-lane="lane-X">: moves its
--                 rows into that lane (data-after="id" puts a row right
--                 under another one, 18's SQL Monitor rows under 06's) and
--                 unhides the lane.  Runs while the page parses.
--   reveal(el)    opens a folded lane / the "+ Show N more" rows that hide
--                 el (called by the chrome's reveal() before a goTo).
-- and on window.AWR_WG:
--   pin(o)        pin window offset o (0 / null / the pinned one = unpin):
--                 its grid column tints amber, every gutter Delta compares
--                 Current against it ("vs 13 Aug"), the chart stripe turns
--                 amber; Esc or leaving the Timeline view clears it.
--   pinned()      the pinned offset or null.
-- At DOMContentLoaded: lane counts / fold / "+ Show N more", the prior
-- values of every grid row (from data-v; shown on hover or pin), the
-- stacked activity columns (Activity lane, and the DB time card chart of
-- the Summary view), the chart (hover tooltip with per-class AAS, legend
-- toggles that restack and rescale, drag-to-zoom with a minimum span,
-- Reset / double-click, compared windows shaded -- Current indigo, pinned
-- amber -- click / Enter on one pins its grid column, release markers).
-- No literal tilde below (SET DEFINE tilde).  Generated from readable JS
-- (the phase-3 scratch js_timeline.js); edit the PUT_LINEs directly.
--
BEGIN
    DBMS_OUTPUT.PUT_LINE('<script>');
    DBMS_OUTPUT.PUT_LINE('(function(){');
    DBMS_OUTPUT.PUT_LINE('var doc=document, W=window.AWR_WG=window.AWR_WG||{}, TL=window.AWR_TL={};');
    DBMS_OUTPUT.PUT_LINE('var H1=36e5, MINUS=''−'';');
    DBMS_OUTPUT.PUT_LINE('function $(s,r){return (r||doc).querySelector(s);}');
    DBMS_OUTPUT.PUT_LINE('function $$(s,r){return Array.prototype.slice.call((r||doc).querySelectorAll(s));}');
    DBMS_OUTPUT.PUT_LINE('function shown(el){return !!el&&el.getClientRects().length>0;}');
    DBMS_OUTPUT.PUT_LINE('function mk(t,c,p){var e=doc.createElement(t);if(c)e.className=c;if(p)p.appendChild(e);return e;}');
    DBMS_OUTPUT.PUT_LINE('function esc(s){return String(s==null?'''':s).replace(/[&<>"]/g,function(c){return {''&'':''&amp;'',''<'':''&lt;'',''>'':''&gt;'',''"'':''&quot;''}[c];});}');
    DBMS_OUTPUT.PUT_LINE('function num(s){if(s==null||s==='''')return null;var v=+s;return isNaN(v)?null:v;}');
    DBMS_OUTPUT.PUT_LINE('function nums(s){return String(s||'''').split('','').map(num);}');
    DBMS_OUTPUT.PUT_LINE('function cssNum(el,n,d){var v=parseFloat(getComputedStyle(el).getPropertyValue(n));return isNaN(v)?d:v;}');
    DBMS_OUTPUT.PUT_LINE('function reduced(){try{return matchMedia(''(prefers-reduced-motion: reduce)'').matches;}catch(e){return false;}}');
    DBMS_OUTPUT.PUT_LINE('/* sql/lib/fmt_num.plsql, client side: about 4 significant digits, k / M / G */');
    DBMS_OUTPUT.PUT_LINE('function grp(n){return String(n).replace(/\B(?=(\d{3})+(?!\d))/g,'','');}');
    DBMS_OUTPUT.PUT_LINE('function fmtNum(p){');
    DBMS_OUTPUT.PUT_LINE('  if(p==null)return ''—'';if(p===0)return ''0'';');
    DBMS_OUTPUT.PUT_LINE('  var a=Math.abs(p),s=p<0?''-'':'''',u='''',v=a,t;');
    DBMS_OUTPUT.PUT_LINE('  if(a>=1e9){v=a/1e9;u='' G'';}else if(a>=1e6){v=a/1e6;u='' M'';}else if(a>=1e4){v=a/1e3;u='' k'';}');
    DBMS_OUTPUT.PUT_LINE('  if(v>=1000)t=grp(Math.round(v));else if(v>=100)t=grp(v.toFixed(1));else if(v>=10)t=v.toFixed(2);else if(v>=1)t=v.toFixed(3);');
    DBMS_OUTPUT.PUT_LINE('  else{var d=Math.min(6,3-Math.floor(Math.log10(v)));if(Math.round(v*1e6)===0)return s+''<0.000001'';t=String(+v.toFixed(d));if(t.charAt(0)!==''0'')t=''0''+t.slice(t.indexOf(''.''));}');
    DBMS_OUTPUT.PUT_LINE('  return s+t+u;');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('/* the page''s one Delta rule (sql/lib/band_glyph.plsql delta_span) */');
    DBMS_OUTPUT.PUT_LINE('function delta(cur,mu){');
    DBMS_OUTPUT.PUT_LINE('  if(cur==null||mu==null||mu===0)return ''—'';');
    DBMS_OUTPUT.PUT_LINE('  var q=cur/mu;');
    DBMS_OUTPUT.PUT_LINE('  if(mu>0&&q>=2)return ''▲ ×''+(q<100?q.toFixed(1):Math.round(q));');
    DBMS_OUTPUT.PUT_LINE('  var p=(cur-mu)/Math.abs(mu)*100;');
    DBMS_OUTPUT.PUT_LINE('  return (p>=0?''▲ '':''▼ '')+Math.abs(p).toFixed(1)+''%'';');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('function aasTxt(v){return v>=10?v.toFixed(0):v>=1?v.toFixed(1):v>=0.01?v.toFixed(2):v.toPrecision(1);}');
    DBMS_OUTPUT.PUT_LINE('function niceStep(max,n){var raw=max/n,p=Math.pow(10,Math.floor(Math.log10(raw))),m=raw/p;return (m<=1?1:m<=2?2:m<=5?5:10)*p;}');
    DBMS_OUTPUT.PUT_LINE('/* the compared windows, oldest first (window.AWR_WIN from 00_params.sql) */');
    DBMS_OUTPUT.PUT_LINE('function wins(){return (window.AWR_WIN&&window.AWR_WIN.w)||[];}');
    DBMS_OUTPUT.PUT_LINE('function winAt(o){var w=wins();for(var i=0;i<w.length;i++)if(w[i].o===+o)return w[i];return null;}');
    DBMS_OUTPUT.PUT_LINE('function idxOf(o){var w=wins();for(var i=0;i<w.length;i++)if(w[i].o===+o)return i;return -1;}');
    DBMS_OUTPUT.PUT_LINE('function offTxt(w){return w.o===0?''Current'':String(w.l).replace(''-'',MINUS);}');
    DBMS_OUTPUT.PUT_LINE('function wcol(c){return (window.AWR_WAIT_COLORS||{})[c]||''#9AA3AD'';}');
    DBMS_OUTPUT.PUT_LINE('var MON=[''Jan'',''Feb'',''Mar'',''Apr'',''May'',''Jun'',''Jul'',''Aug'',''Sep'',''Oct'',''Nov'',''Dec''],DOW=[''Sun'',''Mon'',''Tue'',''Wed'',''Thu'',''Fri'',''Sat''];');
    DBMS_OUTPUT.PUT_LINE('function PT(s){return Date.parse(String(s).replace('' '',''T'')+'':00Z'');}');
    DBMS_OUTPUT.PUT_LINE('function p2(n){return (n<10?''0'':'''')+n;}');
    DBMS_OUTPUT.PUT_LINE('function fDay(t){var d=new Date(t);return d.getUTCDate()+'' ''+MON[d.getUTCMonth()];}');
    DBMS_OUTPUT.PUT_LINE('function fAt(t){var d=new Date(t);return DOW[d.getUTCDay()]+'' ''+fDay(t)+'' ''+p2(d.getUTCHours())+'':''+p2(d.getUTCMinutes());}');
    DBMS_OUTPUT.PUT_LINE('function fHM(t){var d=new Date(t);return p2(d.getUTCHours())+'':''+p2(d.getUTCMinutes());}');
    DBMS_OUTPUT.PUT_LINE('/* ---- 1. lane sources: a section''s rows ride in <template class="tl-src">,');
    DBMS_OUTPUT.PUT_LINE('   the inline script right after it calls take() while the page parses */');
    DBMS_OUTPUT.PUT_LINE('TL.take=function(){');
    DBMS_OUTPUT.PUT_LINE('  var s=doc.currentScript,t=s&&s.previousElementSibling;');
    DBMS_OUTPUT.PUT_LINE('  if(!t||t.tagName!==''TEMPLATE'')return;');
    DBMS_OUTPUT.PUT_LINE('  var lane=doc.getElementById(t.getAttribute(''data-lane'')),box=lane&&$(''.lrows'',lane);');
    DBMS_OUTPUT.PUT_LINE('  if(!box)return;');
    DBMS_OUTPUT.PUT_LINE('  Array.prototype.slice.call(t.content.children).forEach(function(r){');
    DBMS_OUTPUT.PUT_LINE('    var a=r.getAttribute(''data-after''),ref=a?doc.getElementById(a):null;');
    DBMS_OUTPUT.PUT_LINE('    if(ref&&ref.parentNode===box){');
    DBMS_OUTPUT.PUT_LINE('      while(ref.nextElementSibling&&ref.nextElementSibling.getAttribute(''data-after'')===a)ref=ref.nextElementSibling;');
    DBMS_OUTPUT.PUT_LINE('      box.insertBefore(r,ref.nextElementSibling);');
    DBMS_OUTPUT.PUT_LINE('    }else box.appendChild(r);');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('  lane.hidden=false;');
    DBMS_OUTPUT.PUT_LINE('  t.parentNode.removeChild(t);');
    DBMS_OUTPUT.PUT_LINE('};');
    DBMS_OUTPUT.PUT_LINE('/* open whatever hides a Timeline row: a closed lane, the folded rows */');
    DBMS_OUTPUT.PUT_LINE('TL.reveal=function(el){');
    DBMS_OUTPUT.PUT_LINE('  var lane=el&&el.closest?el.closest(''#tl .lane''):null;if(!lane)return;');
    DBMS_OUTPUT.PUT_LINE('  if(lane.classList.contains(''closed'')){lane.classList.remove(''closed'');var b=$(''.lt2'',lane);if(b)b.setAttribute(''aria-expanded'',''true'');}');
    DBMS_OUTPUT.PUT_LINE('  if(el.classList.contains(''more''))showMore(lane);');
    DBMS_OUTPUT.PUT_LINE('  setTimeout(function(){if(W.render)W.render(lane);},0);');
    DBMS_OUTPUT.PUT_LINE('};');
    DBMS_OUTPUT.PUT_LINE('function showMore(lane){lane.classList.add(''showmore'');var b=$(''.xpb'',lane);if(b)b.setAttribute(''aria-expanded'',''true'');if(W.render)W.render(lane);}');
    DBMS_OUTPUT.PUT_LINE('/* ---- 2. lanes: fold toggles, "+ Show N more", counts in the lane head */');
    DBMS_OUTPUT.PUT_LINE('function laneMeta(lane){');
    DBMS_OUTPUT.PUT_LINE('  var m=$(''.gh2 .meta'',lane);if(!m)return[0,0];');
    DBMS_OUTPUT.PUT_LINE('  var rows=$$(''.lrows > .r'',lane),kind=lane.getAttribute(''data-kind''),h='''',lg=0,md=0,nr=0;');
    DBMS_OUTPUT.PUT_LINE('  rows.forEach(function(r){if(r.classList.contains(''twin'')||r.classList.contains(''xpr''))return;var s=r.getAttribute(''data-sev'');if(s===''large'')lg++;else if(s===''moderate'')md++;else if(s)nr++;});');
    DBMS_OUTPUT.PUT_LINE('  if(kind===''scored''){');
    DBMS_OUTPUT.PUT_LINE('    if(lg)h+=''<span><i class="dotk large"></i>''+lg+'' large</span>'';');
    DBMS_OUTPUT.PUT_LINE('    if(md)h+=''<span><i class="dotk moderate"></i>''+md+'' moderate</span>'';');
    DBMS_OUTPUT.PUT_LINE('    if(nr)h+=''<span><i class="dotk typical"></i>''+nr+'' normal</span>'';');
    DBMS_OUTPUT.PUT_LINE('  }else if(kind===''sql''){');
    DBMS_OUTPUT.PUT_LINE('    var pc=$$(''.r:not(.sub) .glf.gp'',lane).length,nw=$$(''.glf.gn'',lane).length,dp=$$(''.glf.gd'',lane).length;');
    DBMS_OUTPUT.PUT_LINE('    if(pc)h+=''<span><b>◆</b> ''+pc+'' plan change''+(pc>1?''s'':'''')+''</span>'';');
    DBMS_OUTPUT.PUT_LINE('    if(nw)h+=''<span><b>✚</b> ''+nw+'' new</span>'';');
    DBMS_OUTPUT.PUT_LINE('    if(dp)h+=''<span><b>▽</b> ''+dp+'' DOP</span>'';');
    DBMS_OUTPUT.PUT_LINE('    if(!h)h=''<span class="muted">ranked, not scored</span>'';');
    DBMS_OUTPUT.PUT_LINE('  }else if(kind===''config''){');
    DBMS_OUTPUT.PUT_LINE('    var n=0,f=0;');
    DBMS_OUTPUT.PUT_LINE('    rows.forEach(function(r){if(!r.classList.contains(''p''))return;n++;var hit=false;$$(''.c'',r).forEach(function(c){if($(''.nd'',c)&&W.markerAt&&W.markerAt(+c.getAttribute(''data-w'')))hit=true;});if(hit)f++;});');
    DBMS_OUTPUT.PUT_LINE('    h=''<span class="muted">''+(f&&f===n?(n>1?''all ''+n+'' under a flag'':''under a flag''):f?f+'' of ''+n+'' under a flag'':n+'' changed'')+''</span>'';');
    DBMS_OUTPUT.PUT_LINE('  }else h=''<span class="muted">''+esc(lane.getAttribute(''data-note'')||''not scored'')+''</span>'';');
    DBMS_OUTPUT.PUT_LINE('  m.innerHTML=h;');
    DBMS_OUTPUT.PUT_LINE('  return [lg,md];');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('function lanes(){');
    DBMS_OUTPUT.PUT_LINE('  var tl=doc.getElementById(''tl'');if(!tl)return;');
    DBMS_OUTPUT.PUT_LINE('  var np=wins().length,tot=[0,0];');
    DBMS_OUTPUT.PUT_LINE('  $$(''.lane'',tl).forEach(function(lane){');
    DBMS_OUTPUT.PUT_LINE('    var more=$$(''.lrows > .r.more'',lane);');
    DBMS_OUTPUT.PUT_LINE('    if(more.length&&!$(''.r.xpr'',lane)){');
    DBMS_OUTPUT.PUT_LINE('      var x=doc.createElement(''div'');x.className=''r xpr'';x.setAttribute(''role'',''row'');');
    DBMS_OUTPUT.PUT_LINE('      var h=''<div class="l" role="rowheader"><button class="xpb" type="button" aria-expanded="false">+ Show ''+more.length+'' more ''+esc(lane.getAttribute(''data-noun'')||''rows'')+''</button></div>'';');
    DBMS_OUTPUT.PUT_LINE('      wins().forEach(function(w){h+=''<div class="c''+(w.o===0?'' cur'':'''')+''" data-w="''+w.o+''"></div>'';});');
    DBMS_OUTPUT.PUT_LINE('      x.innerHTML=h+''<div class="g" role="cell"></div>'';');
    DBMS_OUTPUT.PUT_LINE('      more[0].parentNode.insertBefore(x,more[0]);');
    DBMS_OUTPUT.PUT_LINE('      $(''.xpb'',x).addEventListener(''click'',function(){showMore(lane);});');
    DBMS_OUTPUT.PUT_LINE('    }');
    DBMS_OUTPUT.PUT_LINE('    var n=laneMeta(lane);tot[0]+=n[0];tot[1]+=n[1];');
    DBMS_OUTPUT.PUT_LINE('    var b=$(''.lt2'',lane);');
    DBMS_OUTPUT.PUT_LINE('    if(b)b.addEventListener(''click'',function(){var open=lane.classList.toggle(''closed'')===false;b.setAttribute(''aria-expanded'',String(open));if(open&&W.render)W.render(lane);});');
    DBMS_OUTPUT.PUT_LINE('    var rl=doc.querySelector(''nav.toc a[href="#''+lane.id+''"]'');');
    DBMS_OUTPUT.PUT_LINE('    if(rl){rl.hidden=lane.hidden;if(n[0]){var p=mk(''span'',''cnt c'',rl);p.textContent=n[0];}if(n[1]){var q=mk(''span'',''cnt w'',rl);q.textContent=n[1];}}');
    DBMS_OUTPUT.PUT_LINE('    var jn=$(''.jumpnav a[href="#''+lane.id+''"]'',tl);if(jn)jn.hidden=lane.hidden;');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('  var h2=$(''#timeline > h2'');');
    DBMS_OUTPUT.PUT_LINE('  if(h2&&!$(''.meta'',h2)&&(tot[0]||tot[1])){var m=mk(''span'',''meta'');m.innerHTML=(tot[0]?''<span><i class="dotk large"></i>''+tot[0]+'' large</span>'':'''')+(tot[1]?''<span><i class="dotk moderate"></i>''+tot[1]+'' moderate</span>'':'''');h2.appendChild(m);}');
    DBMS_OUTPUT.PUT_LINE('  if(!np)return;');
    DBMS_OUTPUT.PUT_LINE('  /* a skipped window (no valid snapshot pair) greys its date in the ruler */');
    DBMS_OUTPUT.PUT_LINE('  wins().forEach(function(w){if(w.v!==''N'')return;var h=$(''.ruler .h[data-w="''+w.o+''"]'',tl);if(h){h.classList.add(''skw'');h.title+='' (skipped window: left out of every baseline)'';}});');
    DBMS_OUTPUT.PUT_LINE('  /* the prior values, filled from data-v (shown on hover / pin) */');
    DBMS_OUTPUT.PUT_LINE('  $$(''.r.bars[data-v]'',tl).forEach(function(row){');
    DBMS_OUTPUT.PUT_LINE('    var v=nums(row.getAttribute(''data-v''));');
    DBMS_OUTPUT.PUT_LINE('    $$('':scope > .c[data-w]'',row).forEach(function(c){');
    DBMS_OUTPUT.PUT_LINE('      if($(''.v'',c))return;var x=v[idxOf(c.getAttribute(''data-w''))];');
    DBMS_OUTPUT.PUT_LINE('      c.insertAdjacentHTML(''afterbegin'',x==null?''<span class="v nil" aria-label="no value">–</span>'':''<span class="v">''+fmtNum(x)+''</span>'');');
    DBMS_OUTPUT.PUT_LINE('    });');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('/* ---- 3. pin a window: its column tints, the gutter compares against it */');
    DBMS_OUTPUT.PUT_LINE('var PW=null;');
    DBMS_OUTPUT.PUT_LINE('W.pinned=function(){return PW;};');
    DBMS_OUTPUT.PUT_LINE('function flashCol(o){');
    DBMS_OUTPUT.PUT_LINE('  $$(''#tl .c[data-w="''+o+''"], #tl .ruler .h[data-w="''+o+''"]'').forEach(function(c){c.classList.remove(''colflash'');void c.offsetWidth;c.classList.add(''colflash'');});');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('W.pin=function(o){');
    DBMS_OUTPUT.PUT_LINE('  var tl=doc.getElementById(''tl'');if(!tl)return;');
    DBMS_OUTPUT.PUT_LINE('  o=(o==null||o==='''')?null:+o;');
    DBMS_OUTPUT.PUT_LINE('  var same=(PW!==null&&o===PW),bd=doc.body,gt=doc.getElementById(''tl-gt''),gs=doc.getElementById(''tl-gs'');');
    DBMS_OUTPUT.PUT_LINE('  $$(''.ruler .h[aria-pressed]'',tl).forEach(function(h){h.setAttribute(''aria-pressed'',''false'');});');
    DBMS_OUTPUT.PUT_LINE('  $$(''.pc'',tl).forEach(function(x){x.classList.remove(''pc'');});');
    DBMS_OUTPUT.PUT_LINE('  $$(''.r .g .d1[data-orig]'',tl).forEach(function(d){d.innerHTML=d.getAttribute(''data-orig'');d.removeAttribute(''data-orig'');});');
    DBMS_OUTPUT.PUT_LINE('  if(same||o===null||o===0){');
    DBMS_OUTPUT.PUT_LINE('    PW=null;bd.removeAttribute(''data-pw'');');
    DBMS_OUTPUT.PUT_LINE('    if(gt)gt.textContent=''vs prior mean'';if(gs)gs.textContent=''click a date to pin'';');
    DBMS_OUTPUT.PUT_LINE('    axDraw();return;');
    DBMS_OUTPUT.PUT_LINE('  }');
    DBMS_OUTPUT.PUT_LINE('  var w=winAt(o),i=idxOf(o);if(!w)return;');
    DBMS_OUTPUT.PUT_LINE('  PW=o;bd.setAttribute(''data-pw'',String(o));');
    DBMS_OUTPUT.PUT_LINE('  var h=$(''.ruler .h[data-w="''+o+''"]'',tl);if(h)h.setAttribute(''aria-pressed'',''true'');');
    DBMS_OUTPUT.PUT_LINE('  $$(''[data-w="''+o+''"]'',tl).forEach(function(x){if(!x.closest(''.flags''))x.classList.add(''pc'');});');
    DBMS_OUTPUT.PUT_LINE('  $$(''.r.bars[data-v]'',tl).forEach(function(row){');
    DBMS_OUTPUT.PUT_LINE('    var d=$('':scope > .g .d1'',row);if(!d)return;');
    DBMS_OUTPUT.PUT_LINE('    var v=nums(row.getAttribute(''data-v''));');
    DBMS_OUTPUT.PUT_LINE('    d.setAttribute(''data-orig'',d.innerHTML);');
    DBMS_OUTPUT.PUT_LINE('    d.textContent=delta(v[v.length-1],v[i])+'' vs ''+w.d;');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('  if(gt){gt.innerHTML=''vs ''+esc(w.d)+'' <button type="button" class="unpin" aria-label="Clear the pinned window">clear</button>'';$(''.unpin'',gt).addEventListener(''click'',function(){W.pin(null);});}');
    DBMS_OUTPUT.PUT_LINE('  if(gs)gs.textContent=''band stays vs prior mean'';');
    DBMS_OUTPUT.PUT_LINE('  axDraw();');
    DBMS_OUTPUT.PUT_LINE('};');
    DBMS_OUTPUT.PUT_LINE('doc.addEventListener(''click'',function(ev){');
    DBMS_OUTPUT.PUT_LINE('  var h=ev.target&&ev.target.closest?ev.target.closest(''#tl .ruler .h[data-w]''):null;if(!h)return;');
    DBMS_OUTPUT.PUT_LINE('  var o=+h.getAttribute(''data-w'');');
    DBMS_OUTPUT.PUT_LINE('  if(o===0){W.pin(null);flashCol(0);}else W.pin(o);');
    DBMS_OUTPUT.PUT_LINE('});');
    DBMS_OUTPUT.PUT_LINE('doc.addEventListener(''keydown'',function(ev){if(ev.key===''Escape''&&PW!==null)W.pin(null);});');
    DBMS_OUTPUT.PUT_LINE('doc.addEventListener(''awr:view'',function(ev){');
    DBMS_OUTPUT.PUT_LINE('  var v=ev.detail&&ev.detail.view;');
    DBMS_OUTPUT.PUT_LINE('  if(v!==''timeline''&&PW!==null)W.pin(null);');
    DBMS_OUTPUT.PUT_LINE('  if(v===''timeline'')setTimeout(function(){axDraw(true);sync();startAtCurrent();},50);');
    DBMS_OUTPUT.PUT_LINE('});');
    DBMS_OUTPUT.PUT_LINE('/* ---- 4. tooltip over the grid and the full-span chart */');
    DBMS_OUTPUT.PUT_LINE('var tip=null;');
    DBMS_OUTPUT.PUT_LINE('function tipOn(html,e){if(!tip)return;tip.innerHTML=html;tip.hidden=false;place(e);}');
    DBMS_OUTPUT.PUT_LINE('function tipOff(){if(tip)tip.hidden=true;}');
    DBMS_OUTPUT.PUT_LINE('function place(e){');
    DBMS_OUTPUT.PUT_LINE('  var x=e.clientX+14,y=e.clientY+16,w=tip.offsetWidth,h=tip.offsetHeight;');
    DBMS_OUTPUT.PUT_LINE('  if(x+w>innerWidth-8)x=e.clientX-w-12;if(y+h>innerHeight-8)y=e.clientY-h-12;');
    DBMS_OUTPUT.PUT_LINE('  tip.style.left=Math.max(8,x)+''px'';tip.style.top=Math.max(8,y)+''px'';');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('function ashRows(get,cls){');
    DBMS_OUTPUT.PUT_LINE('  var h='''',tot=0,A=AX;');
    DBMS_OUTPUT.PUT_LINE('  for(var c=A.classes.length-1;c>=0;c--){if(cls&&!cls[c])continue;var v=get(c);if(v==null)continue;tot+=v;');
    DBMS_OUTPUT.PUT_LINE('    if(v>=0.005)h+=''<div class="tr2"><span><i class="sw" style="--sw:''+wcol(A.classes[c])+''"></i>''+esc(A.classes[c])+''</span><b>''+v.toFixed(2)+''</b></div>'';}');
    DBMS_OUTPUT.PUT_LINE('  return h+''<div class="tr2 tsum"><span>''+(cls?''Total, shown classes'':''Total'')+''</span><b>''+tot.toFixed(1)+'' AAS</b></div>'';');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('function cellTip(cell){');
    DBMS_OUTPUT.PUT_LINE('  var row=cell.closest(''.r'');if(!row||!row.getAttribute(''data-name''))return '''';');
    DBMS_OUTPUT.PUT_LINE('  var o=+cell.getAttribute(''data-w''),w=winAt(o),i=idxOf(o);if(!w)return '''';');
    DBMS_OUTPUT.PUT_LINE('  var head=''<b>''+esc(row.getAttribute(''data-name''))+''</b><br><span class="tm">''+esc(w.t)+'', ''+offTxt(w)+(w.v===''N''?'', skipped window'':'''')+''</span><br>'';');
    DBMS_OUTPUT.PUT_LINE('  if(row.classList.contains(''ash'')&&AX&&AX.win)return head+ashRows(function(c){return AX.win[c][i];});');
    DBMS_OUTPUT.PUT_LINE('  if(row.classList.contains(''p''))return head+''<b>''+esc(cell.getAttribute(''data-pv'')||'''')+''</b>'';');
    DBMS_OUTPUT.PUT_LINE('  var v=nums(row.getAttribute(''data-v''))[i];');
    DBMS_OUTPUT.PUT_LINE('  if(v==null)return head+''<span class="tm">''+(row.classList.contains(''q'')||row.classList.contains(''o'')?''not in the top list in this window'':''no value in this window'')+''</span>'';');
    DBMS_OUTPUT.PUT_LINE('  var g=$(''.glf'',cell);');
    DBMS_OUTPUT.PUT_LINE('  return head+''<b>''+fmtNum(v)+''</b> ''+esc(row.getAttribute(''data-unit'')||'''')+(g?''<br>''+esc(g.title):'''');');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('doc.addEventListener(''mouseover'',function(e){');
    DBMS_OUTPUT.PUT_LINE('  var t=e.target;if(!t||!t.closest||!tip)return;');
    DBMS_OUTPUT.PUT_LINE('  if(t.closest(''#ax-plot''))return;');
    DBMS_OUTPUT.PUT_LINE('  var c=t.closest(''#tl .lrows .c[data-w]'');');
    DBMS_OUTPUT.PUT_LINE('  if(c){var s=cellTip(c);if(s){tipOn(s,e);return;}}');
    DBMS_OUTPUT.PUT_LINE('  tipOff();');
    DBMS_OUTPUT.PUT_LINE('});');
    DBMS_OUTPUT.PUT_LINE('doc.addEventListener(''mousemove'',function(e){if(tip&&!tip.hidden&&!(e.target.closest&&e.target.closest(''#ax-plot'')))place(e);},{passive:true});');
    DBMS_OUTPUT.PUT_LINE('doc.addEventListener(''scroll'',tipOff,{passive:true});');
    DBMS_OUTPUT.PUT_LINE('/* ---- 5. stacked activity per window: the Activity lane and the DB time card */');
    DBMS_OUTPUT.PUT_LINE('function stack(row,vals,opt){');
    DBMS_OUTPUT.PUT_LINE('  var A=AX,np=wins().length,tot=[],mx=0;');
    DBMS_OUTPUT.PUT_LINE('  for(var i=0;i<np;i++){var s=0;A.classes.forEach(function(c,k){s+=vals[k][i]||0;});tot.push(s);if(s>mx)mx=s;}');
    DBMS_OUTPUT.PUT_LINE('  if(!(mx>0))return false;');
    DBMS_OUTPUT.PUT_LINE('  var step=niceStep(mx,3),max=mx*1.04,ticks=[];for(var t=step;t<=max+1e-9;t+=step)ticks.push(t);');
    DBMS_OUTPUT.PUT_LINE('  var bh=cssNum(row,''--bh'',148),bb=cssNum(row,''--bb'',6),GAP=2;');
    DBMS_OUTPUT.PUT_LINE('  $$('':scope > .c[data-w]'',row).forEach(function(c){');
    DBMS_OUTPUT.PUT_LINE('    var i=idxOf(c.getAttribute(''data-w''));if(i<0)return;');
    DBMS_OUTPUT.PUT_LINE('    $$(''.stk,.gline,.dl'',c).forEach(function(x){x.parentNode.removeChild(x);});');
    DBMS_OUTPUT.PUT_LINE('    ticks.forEach(function(t){var g=mk(''i'',''gline'',c);g.style.bottom=(bb+t/max*bh)+''px'';});');
    DBMS_OUTPUT.PUT_LINE('    var st=mk(''div'',''stk'',c),y=0,segs=[];');
    DBMS_OUTPUT.PUT_LINE('    A.classes.forEach(function(name,k){');
    DBMS_OUTPUT.PUT_LINE('      var v=vals[k][i]||0,h=v/max*bh;if(h<0.4)return;');
    DBMS_OUTPUT.PUT_LINE('      var s=mk(''i'','''',st);s.style.background=wcol(name);s.style.bottom=y+''px'';s.style.height=Math.max(0.6,h-(h>4?GAP:0))+''px'';');
    DBMS_OUTPUT.PUT_LINE('      segs.push({n:name,v:v,mid:y+h/2});y+=h;');
    DBMS_OUTPUT.PUT_LINE('    });');
    DBMS_OUTPUT.PUT_LINE('    if(c.classList.contains(''cur'')&&opt.labels){');
    DBMS_OUTPUT.PUT_LINE('      var last=-99;');
    DBMS_OUTPUT.PUT_LINE('      segs.slice().sort(function(a,b){return b.v-a.v;}).slice(0,2).sort(function(a,b){return a.mid-b.mid;}).forEach(function(s){');
    DBMS_OUTPUT.PUT_LINE('        if(s.v/max*bh<8)return;');
    DBMS_OUTPUT.PUT_LINE('        var pos=Math.max(s.mid,last+16);last=pos;');
    DBMS_OUTPUT.PUT_LINE('        var d=mk(''span'',''dl'',c);d.innerHTML=''<i class="sw" style="--sw:''+wcol(s.n)+''"></i>''+aasTxt(s.v);d.title=s.n;d.style.bottom=(bb+pos)+''px'';');
    DBMS_OUTPUT.PUT_LINE('      });');
    DBMS_OUTPUT.PUT_LINE('    }');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('  var ax=$(''.axn'',row);');
    DBMS_OUTPUT.PUT_LINE('  if(ax){ax.innerHTML='''';[0].concat(ticks).forEach(function(t){var i=mk(''i'','''',ax);i.textContent=t;i.style.bottom=(bb+t/max*bh)+''px'';});}');
    DBMS_OUTPUT.PUT_LINE('  return true;');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('function activity(){');
    DBMS_OUTPUT.PUT_LINE('  if(!AX||!AX.win||!AX.classes.length)return;');
    DBMS_OUTPUT.PUT_LINE('  $$(''#tl .r.ash'').forEach(function(row){stack(row,AX.win,{labels:true});});');
    DBMS_OUTPUT.PUT_LINE('  /* the DB time card: the same per-window ASH, stacked by wait class */');
    DBMS_OUTPUT.PUT_LINE('  var row=$(''#f-dbtime .fc-main .wg .r.bars'');if(!row)return;');
    DBMS_OUTPUT.PUT_LINE('  var np=wins().length,cur=[];');
    DBMS_OUTPUT.PUT_LINE('  AX.classes.forEach(function(c,k){cur.push([c,AX.win[k][np-1]||0,k]);});');
    DBMS_OUTPUT.PUT_LINE('  cur.sort(function(a,b){return b[1]-a[1];});');
    DBMS_OUTPUT.PUT_LINE('  row.classList.remove(''bars'');row.classList.add(''ash'');');
    DBMS_OUTPUT.PUT_LINE('  if(!stack(row,AX.win,{labels:true})){row.classList.remove(''ash'');row.classList.add(''bars'');return;}');
    DBMS_OUTPUT.PUT_LINE('  var tot=0;cur.forEach(function(x){tot+=x[1];});');
    DBMS_OUTPUT.PUT_LINE('  $$('':scope > .c'',row).forEach(function(c){var v=$(''.v'',c);if(!v)return;if(c.classList.contains(''cur''))v.textContent=tot.toFixed(2);else v.parentNode.removeChild(v);});');
    DBMS_OUTPUT.PUT_LINE('  $$('':scope > .c > i'',row).forEach(function(x){x.parentNode.removeChild(x);});');
    DBMS_OUTPUT.PUT_LINE('  var ul=doc.createElement(''ul'');ul.className=''leg fcleg'';ul.setAttribute(''aria-label'',''Active sessions by wait class, ASH'');');
    DBMS_OUTPUT.PUT_LINE('  ul.innerHTML=cur.filter(function(x){return x[1]>0;}).map(function(x){return ''<li><i class="sw" style="--sw:''+wcol(x[0])+''"></i>''+esc(x[0])+''</li>'';}).join('''');');
    DBMS_OUTPUT.PUT_LINE('  var wg=row.closest(''.wg'');wg.parentNode.insertBefore(ul,wg);');
    DBMS_OUTPUT.PUT_LINE('  wg.title=''Active sessions (ASH) per compared window, stacked by wait class; Current total ''+tot.toFixed(2)+'' AAS'';');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('/* ---- 6. the full-span ASH chart: hover, legend, brush zoom, windows, markers */');
    DBMS_OUTPUT.PUT_LINE('var AX=null,ax=null,cvs=null;');
    DBMS_OUTPUT.PUT_LINE('function tw(t){if(!cvs)cvs=doc.createElement(''canvas'').getContext(''2d'');cvs.font=''11px ui-sans-serif, -apple-system, "Segoe UI", Inter, Roboto, system-ui, sans-serif'';return cvs.measureText(t).width;}');
    DBMS_OUTPUT.PUT_LINE('function axInit(){');
    DBMS_OUTPUT.PUT_LINE('  AX=(window.AWR_DATA||{}).ashx||null;');
    DBMS_OUTPUT.PUT_LINE('  var panel=doc.getElementById(''tl-ash'');if(!panel||!AX||!AX.t0)return;');
    DBMS_OUTPUT.PUT_LINE('  panel.hidden=false;');
    DBMS_OUTPUT.PUT_LINE('  if(!AX.classes||!AX.classes.length){var n=$(''#ax-empty'',panel);if(n)n.hidden=false;var p=$(''#ax-plot'',panel);if(p)p.hidden=true;return;}');
    DBMS_OUTPUT.PUT_LINE('  var bh=AX.bh*H1,t0=PT(AX.t0),end=PT(AX.end),n2=AX.vals[0].length,T=[],T1=[];');
    DBMS_OUTPUT.PUT_LINE('  for(var i=0;i<n2;i++){T.push(t0+i*bh);T1.push(Math.min(t0+(i+1)*bh,end));}');
    DBMS_OUTPUT.PUT_LINE('  ax={svg:$(''#ax-svg''),plot:$(''#ax-plot''),br:$(''#ax-brush''),reset:$(''#ax-reset''),range:$(''#ax-range''),T:T,T1:T1,full:[t0,end],dom:[t0,end],');
    DBMS_OUTPUT.PUT_LINE('      vis:AX.classes.map(function(){return true;}),win:wins().map(function(w){return [PT(w.s),PT(w.e)];}),g:null,drag:null,w:0,');
    DBMS_OUTPUT.PUT_LINE('      min:Math.max(3*bh,Math.min(12*H1,(end-t0)/4)),bhTxt:AX.bh===1?''hourly'':(Math.round(AX.bh*100)/100)+''-hour averages''};');
    DBMS_OUTPUT.PUT_LINE('  var lg=$(''#ax-lg'');');
    DBMS_OUTPUT.PUT_LINE('  if(lg){lg.innerHTML=AX.classes.map(function(c,k){return ''<button type="button" class="axc" data-c="''+k+''" aria-pressed="true" title="Show or hide ''+esc(c)+''"><i class="sw" style="--sw:''+wcol(c)+''" aria-hidden="true"></i>''+esc(c)+''</button>'';}).join('''');');
    DBMS_OUTPUT.PUT_LINE('    $$(''.axc'',lg).forEach(function(b){b.addEventListener(''click'',function(){var c=+b.getAttribute(''data-c'');ax.vis[c]=!ax.vis[c];b.setAttribute(''aria-pressed'',String(ax.vis[c]));axDraw(true);});});}');
    DBMS_OUTPUT.PUT_LINE('  var s=ax.svg;');
    DBMS_OUTPUT.PUT_LINE('  s.addEventListener(''mousemove'',axHover);');
    DBMS_OUTPUT.PUT_LINE('  s.addEventListener(''mouseleave'',function(){tipOff();axHide();});');
    DBMS_OUTPUT.PUT_LINE('  s.addEventListener(''mousedown'',function(e){');
    DBMS_OUTPUT.PUT_LINE('    if(e.button!==0||!ax.g)return;e.preventDefault();');
    DBMS_OUTPUT.PUT_LINE('    /* the second press of a double-click resets the zoom (the chart is redrawn');
    DBMS_OUTPUT.PUT_LINE('       between the two presses, so a dblclick event may never fire) and undoes');
    DBMS_OUTPUT.PUT_LINE('       the pin the first press made on a window stripe */');
    DBMS_OUTPUT.PUT_LINE('    if(e.detail>=2){if(ax.sel&&Date.now()-ax.sel.t<700)W.pin(ax.sel.prev);ax.sel=null;ax.drag=null;ax.dom=ax.full.slice();axDraw(true);return;}');
    DBMS_OUTPUT.PUT_LINE('    var wh=e.target.closest(''.xwh'');ax.drag={x0:e.clientX,moved:false,w:wh?+wh.getAttribute(''data-i''):null};');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('  doc.addEventListener(''mousemove'',function(e){');
    DBMS_OUTPUT.PUT_LINE('    var dg=ax.drag;if(!dg)return;');
    DBMS_OUTPUT.PUT_LINE('    if(!dg.moved&&Math.abs(e.clientX-dg.x0)<5)return;');
    DBMS_OUTPUT.PUT_LINE('    dg.moved=true;tipOff();');
    DBMS_OUTPUT.PUT_LINE('    var r=ax.svg.getBoundingClientRect(),sc=r.width/ax.g.W,mn=r.left+ax.g.padL*sc,mx=r.left+(ax.g.W-ax.g.padR)*sc;');
    DBMS_OUTPUT.PUT_LINE('    var a=Math.max(mn,Math.min(dg.x0,e.clientX)),b=Math.min(mx,Math.max(dg.x0,e.clientX));');
    DBMS_OUTPUT.PUT_LINE('    ax.br.hidden=false;ax.br.style.left=(a-r.left)+''px'';ax.br.style.width=Math.max(0,b-a)+''px'';');
    DBMS_OUTPUT.PUT_LINE('    ax.br.style.top=(ax.g.top*sc)+''px'';ax.br.style.height=(ax.g.ph*sc)+''px'';dg.a=a;dg.b=b;');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('  doc.addEventListener(''mouseup'',function(){');
    DBMS_OUTPUT.PUT_LINE('    var dg=ax.drag;if(!dg)return;ax.drag=null;ax.br.hidden=true;');
    DBMS_OUTPUT.PUT_LINE('    if(dg.moved){if(dg.b-dg.a>6)axZoom(axTime(dg.a),axTime(dg.b));return;}');
    DBMS_OUTPUT.PUT_LINE('    if(dg.w!=null){ax.sel={prev:PW,t:Date.now()};axSelect(dg.w);}');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('  s.addEventListener(''dblclick'',function(){ax.dom=ax.full.slice();axDraw(true);});');
    DBMS_OUTPUT.PUT_LINE('  s.addEventListener(''keydown'',function(e){var wh=e.target.closest&&e.target.closest(''.xwh'');if(wh&&(e.key===''Enter''||e.key==='' '')){e.preventDefault();axSelect(+wh.getAttribute(''data-i''));}});');
    DBMS_OUTPUT.PUT_LINE('  ax.reset.addEventListener(''click'',function(){ax.dom=ax.full.slice();axDraw(true);});');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('function axHide(){var hb=doc.getElementById(''ax-hb''),ch=doc.getElementById(''ax-ch'');if(hb){hb.setAttribute(''visibility'',''hidden'');ch.setAttribute(''visibility'',''hidden'');}}');
    DBMS_OUTPUT.PUT_LINE('function axDraw(force){');
    DBMS_OUTPUT.PUT_LINE('  if(!ax||!shown(ax.plot))return;');
    DBMS_OUTPUT.PUT_LINE('  var Wd=Math.max(480,ax.plot.clientWidth);if(!force&&ax.w===Wd&&ax.g&&ax.pw===PW)return;ax.w=Wd;ax.pw=PW;');
    DBMS_OUTPUT.PUT_LINE('  var top=44,ph=236,bot=26,padL=40,padR=14,H=top+ph+bot,pw=Wd-padL-padR,d0=ax.dom[0],d1=ax.dom[1],A=AX;');
    DBMS_OUTPUT.PUT_LINE('  ax.svg.setAttribute(''viewBox'',''0 0 ''+Wd+'' ''+H);ax.svg.setAttribute(''height'',H);');
    DBMS_OUTPUT.PUT_LINE('  var X=function(t){return padL+pw*(t-d0)/(d1-d0);};');
    DBMS_OUTPUT.PUT_LINE('  var idx=[];for(var i=0;i<ax.T.length;i++)if(ax.T1[i]>d0&&ax.T[i]<d1)idx.push(i);');
    DBMS_OUTPUT.PUT_LINE('  var tot=idx.map(function(i){var s=0;A.vals.forEach(function(v,c){if(ax.vis[c])s+=v[i]||0;});return s;});');
    DBMS_OUTPUT.PUT_LINE('  var mx=Math.max.apply(null,tot.concat([0.05])),step=niceStep(mx,4),ymax=Math.ceil(mx/step-1e-9)*step;');
    DBMS_OUTPUT.PUT_LINE('  var Y=function(v){return top+ph-ph*v/ymax;};');
    DBMS_OUTPUT.PUT_LINE('  var s=''<defs><clipPath id="ax-clip"><rect x="''+padL+''" y="''+(top-6)+''" width="''+pw+''" height="''+(ph+6)+''"/></clipPath></defs>'';');
    DBMS_OUTPUT.PUT_LINE('  for(var v=0;v<=ymax+1e-9;v+=step){var dec=step<1?(step<0.1?2:1):0;');
    DBMS_OUTPUT.PUT_LINE('    s+=''<line class="gl" x1="''+padL+''" x2="''+(Wd-padR)+''" y1="''+Y(v).toFixed(1)+''" y2="''+Y(v).toFixed(1)+''"/><text class="at" x="''+(padL-6)+''" y="''+(Y(v)+4).toFixed(1)+''" text-anchor="end">''+v.toFixed(dec)+''</text>'';}');
    DBMS_OUTPUT.PUT_LINE('  s+=''<text class="at" x="''+(padL-6)+''" y="''+(top-10)+''" text-anchor="end">AAS</text><g clip-path="url(#ax-clip)">'';');
    DBMS_OUTPUT.PUT_LINE('  var lo=idx.map(function(){return 0;});');
    DBMS_OUTPUT.PUT_LINE('  A.vals.forEach(function(vals,c){');
    DBMS_OUTPUT.PUT_LINE('    if(!ax.vis[c]||!idx.length)return;');
    DBMS_OUTPUT.PUT_LINE('    var hi=lo.map(function(l,j){return l+(vals[idx[j]]||0);}),d='''';');
    DBMS_OUTPUT.PUT_LINE('    idx.forEach(function(i,j){var y=Y(hi[j]).toFixed(1);d+=(j?''L'':''M'')+X(ax.T[i]).toFixed(1)+'' ''+y+''L''+X(ax.T1[i]).toFixed(1)+'' ''+y;});');
    DBMS_OUTPUT.PUT_LINE('    for(var j=idx.length-1;j>=0;j--){var y0=Y(lo[j]).toFixed(1);d+=''L''+X(ax.T1[idx[j]]).toFixed(1)+'' ''+y0+''L''+X(ax.T[idx[j]]).toFixed(1)+'' ''+y0;}');
    DBMS_OUTPUT.PUT_LINE('    s+=''<path class="xa" fill="''+wcol(A.classes[c])+''" d="''+d+''Z"/>'';lo=hi;');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('  s+=''<rect id="ax-hb" class="xbk" x="0" y="''+top+''" width="0" height="''+ph+''" visibility="hidden"/>'';');
    DBMS_OUTPUT.PUT_LINE('  var ws=wins(),hit=[],cur=ws.length-1;');
    DBMS_OUTPUT.PUT_LINE('  ax.win.forEach(function(r,i){');
    DBMS_OUTPUT.PUT_LINE('    var xa=X(r[0]),xb=X(r[1]);if(xb<padL-2||xa>Wd-padR+2)return;');
    DBMS_OUTPUT.PUT_LINE('    var w=Math.max(i===cur?4:3,xb-xa),x=(xa+xb)/2-w/2,cls=(i===cur?'' cur'':'''')+(ws[i].o===PW?'' on'':'''')+(ws[i].v===''N''?'' sk'':'''');');
    DBMS_OUTPUT.PUT_LINE('    s+=''<rect class="xw''+cls+''" x="''+x.toFixed(1)+''" y="''+top+''" width="''+w.toFixed(1)+''" height="''+ph+''"/><rect class="xwc''+cls+''" x="''+x.toFixed(1)+''" y="''+(top-5)+''" width="''+w.toFixed(1)+''" height="4" rx="1"/>'';');
    DBMS_OUTPUT.PUT_LINE('    hit.push([i,x,w]);');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('  s+=''</g><line class="ax" x1="''+padL+''" x2="''+(Wd-padR)+''" y1="''+(top+ph)+''" y2="''+(top+ph)+''"/>'';');
    DBMS_OUTPUT.PUT_LINE('  /* x ticks: the smallest interval that leaves about 88 px per label, counted from');
    DBMS_OUTPUT.PUT_LINE('     midnight of the Current window''s day (weekly ticks land on its weekday) */');
    DBMS_OUTPUT.PUT_LINE('  var IVS=[1,2,3,6,12,24,48,168,336,672].map(function(h){return h*H1;}),iv=IVS[IVS.length-1];');
    DBMS_OUTPUT.PUT_LINE('  for(var q=0;q<IVS.length;q++){if(pw*IVS[q]/(d1-d0)>=88){iv=IVS[q];break;}}');
    DBMS_OUTPUT.PUT_LINE('  var org=Math.floor(ax.win[cur][0]/864e5)*864e5;');
    DBMS_OUTPUT.PUT_LINE('  for(var tt=org+Math.ceil((d0-org)/iv)*iv;tt<=d1;tt+=iv){');
    DBMS_OUTPUT.PUT_LINE('    var xt=X(tt);if(xt<padL+12||xt>Wd-padR-12)continue;');
    DBMS_OUTPUT.PUT_LINE('    var lab=(iv>=24*H1||new Date(tt).getUTCHours()===0)?fDay(tt):fHM(tt);');
    DBMS_OUTPUT.PUT_LINE('    s+=''<line class="ax" x1="''+xt.toFixed(1)+''" x2="''+xt.toFixed(1)+''" y1="''+(top+ph)+''" y2="''+(top+ph+4)+''"/><text class="at" x="''+xt.toFixed(1)+''" y="''+(top+ph+18)+''" text-anchor="middle">''+lab+''</text>'';');
    DBMS_OUTPUT.PUT_LINE('  }');
    DBMS_OUTPUT.PUT_LINE('  /* release markers: a flag in a two-tier band, a line through the plot */');
    DBMS_OUTPUT.PUT_LINE('  var tiers=[[],[]];');
    DBMS_OUTPUT.PUT_LINE('  (W.markers?W.markers():[]).forEach(function(m){');
    DBMS_OUTPUT.PUT_LINE('    var x=X(PT(m.at));if(x<padL||x>Wd-padR)return;');
    DBMS_OUTPUT.PUT_LINE('    [m.l,m.s].some(function(lb){');
    DBMS_OUTPUT.PUT_LINE('      var w=tw(lb)+12,x0=x+w>Wd-padR?x-w:x,end=x0!==x;');
    DBMS_OUTPUT.PUT_LINE('      for(var L=0;L<2;L++){');
    DBMS_OUTPUT.PUT_LINE('        if(tiers[L].some(function(r){return x0<r[1]+6&&x0+w>r[0]-6;}))continue;');
    DBMS_OUTPUT.PUT_LINE('        tiers[L].push([x0,x0+w]);var y=2+L*19;');
    DBMS_OUTPUT.PUT_LINE('        s+=''<line class="cfl" x1="''+x.toFixed(1)+''" x2="''+x.toFixed(1)+''" y1="''+(y+16)+''" y2="''+(top+ph)+''"/><line class="cf" x1="''+x.toFixed(1)+''" x2="''+x.toFixed(1)+''" y1="''+y+''" y2="''+(y+16)+''"/>''');
    DBMS_OUTPUT.PUT_LINE('          +''<rect class="cfh" x="''+(end?x0:x+1).toFixed(1)+''" y="''+y+''" width="''+(w-1)+''" height="16" rx="2"/>''');
    DBMS_OUTPUT.PUT_LINE('          +''<text class="cft" x="''+(end?x-6:x+6).toFixed(1)+''" y="''+(y+12)+''" text-anchor="''+(end?''end'':''start'')+''"><title>''+esc(m.l+'', ''+m.t)+''</title>''+esc(lb)+''</text>'';');
    DBMS_OUTPUT.PUT_LINE('        return true;');
    DBMS_OUTPUT.PUT_LINE('      }');
    DBMS_OUTPUT.PUT_LINE('      return false;');
    DBMS_OUTPUT.PUT_LINE('    });');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('  s+=''<line id="ax-ch" class="xch" x1="0" x2="0" y1="''+top+''" y2="''+(top+ph)+''" visibility="hidden"/>'';');
    DBMS_OUTPUT.PUT_LINE('  hit.forEach(function(q){');
    DBMS_OUTPUT.PUT_LINE('    var i=q[0],w=ws[i],hw=Math.max(12,q[2]),hx=q[1]+q[2]/2-hw/2;');
    DBMS_OUTPUT.PUT_LINE('    s+=''<rect class="xwh" data-i="''+i+''" data-w="''+w.o+''" x="''+hx.toFixed(1)+''" y="''+(top-6)+''" width="''+hw.toFixed(1)+''" height="''+(ph+6)+''" tabindex="0" role="button" aria-label="''');
    DBMS_OUTPUT.PUT_LINE('      +esc((w.o===0?''Current window, '':offTxt(w)+'' window, '')+w.t+(w.o===0?'''':''. Pin its column in the grid''))+''"/>'';');
    DBMS_OUTPUT.PUT_LINE('  });');
    DBMS_OUTPUT.PUT_LINE('  ax.svg.innerHTML=s;');
    DBMS_OUTPUT.PUT_LINE('  ax.g={X:X,W:Wd,padL:padL,padR:padR,top:top,ph:ph,pw:pw,d0:d0,d1:d1};');
    DBMS_OUTPUT.PUT_LINE('  var zoomed=d0>ax.full[0]||d1<ax.full[1];');
    DBMS_OUTPUT.PUT_LINE('  ax.reset.hidden=!zoomed;');
    DBMS_OUTPUT.PUT_LINE('  ax.range.textContent=zoomed?fAt(d0)+'' to ''+fAt(d1)+'', zoomed'':fDay(ax.full[0])+'' to ''+fDay(ax.full[1])+'', ''+ax.bhTxt;');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('function axTime(cx){var r=ax.svg.getBoundingClientRect(),x=(cx-r.left)*ax.g.W/r.width;return ax.g.d0+(x-ax.g.padL)/ax.g.pw*(ax.g.d1-ax.g.d0);}');
    DBMS_OUTPUT.PUT_LINE('function axHover(e){');
    DBMS_OUTPUT.PUT_LINE('  if(!ax.g||ax.drag&&ax.drag.moved)return;');
    DBMS_OUTPUT.PUT_LINE('  var hb=doc.getElementById(''ax-hb''),ch=doc.getElementById(''ax-ch''),wh=e.target.closest&&e.target.closest(''.xwh'');');
    DBMS_OUTPUT.PUT_LINE('  if(wh){');
    DBMS_OUTPUT.PUT_LINE('    var i=+wh.getAttribute(''data-i''),w=wins()[i];axHide();');
    DBMS_OUTPUT.PUT_LINE('    tipOn(''<b>''+esc(w.t)+''</b><br><span class="tm">''+(w.o===0?''Current window'':offTxt(w)+'' window'')+(w.v===''N''?'', skipped'':'''')+'', the window itself</span>''');
    DBMS_OUTPUT.PUT_LINE('      +ashRows(function(c){return AX.win[c][i];},ax.vis)+(w.o===0?'''':''<span class="tm">Click to pin this column below</span>''),e);');
    DBMS_OUTPUT.PUT_LINE('    return;');
    DBMS_OUTPUT.PUT_LINE('  }');
    DBMS_OUTPUT.PUT_LINE('  var t=axTime(e.clientX),k=-1;');
    DBMS_OUTPUT.PUT_LINE('  for(var j=0;j<ax.T.length;j++)if(ax.T[j]<=t&&t<ax.T1[j]){k=j;break;}');
    DBMS_OUTPUT.PUT_LINE('  if(k<0||t<ax.g.d0||t>ax.g.d1){axHide();tipOff();return;}');
    DBMS_OUTPUT.PUT_LINE('  var xa=Math.max(ax.g.padL,ax.g.X(ax.T[k])),xb=Math.min(ax.g.W-ax.g.padR,ax.g.X(ax.T1[k])),x=ax.g.X(t);');
    DBMS_OUTPUT.PUT_LINE('  hb.setAttribute(''x'',xa.toFixed(1));hb.setAttribute(''width'',Math.max(1,xb-xa).toFixed(1));hb.setAttribute(''visibility'',''visible'');');
    DBMS_OUTPUT.PUT_LINE('  ch.setAttribute(''x1'',x.toFixed(1));ch.setAttribute(''x2'',x.toFixed(1));ch.setAttribute(''visibility'',''visible'');');
    DBMS_OUTPUT.PUT_LINE('  var hrs=Math.round((ax.T1[k]-ax.T[k])/H1*100)/100;');
    DBMS_OUTPUT.PUT_LINE('  tipOn(''<b>''+fAt(ax.T[k])+''–''+fHM(ax.T1[k])+''</b><br><span class="tm">''+(hrs===1?''1-hour'':hrs+''-hour'')+'' average</span>''+ashRows(function(c){return AX.vals[c][k];},ax.vis),e);');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('function axSelect(i){');
    DBMS_OUTPUT.PUT_LINE('  var w=wins()[i];if(!w)return;');
    DBMS_OUTPUT.PUT_LINE('  if(w.o===0){if(PW!==null)W.pin(null);}else W.pin(w.o);');
    DBMS_OUTPUT.PUT_LINE('  flashCol(w.o);');
    DBMS_OUTPUT.PUT_LINE('  var tl=doc.getElementById(''tl'');if(!tl)return;');
    DBMS_OUTPUT.PUT_LINE('  var r=tl.getBoundingClientRect();if(r.top>innerHeight-220)window.scrollBy({top:r.top-innerHeight+320,behavior:reduced()?''auto'':''smooth''});');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('function axZoom(a,b){');
    DBMS_OUTPUT.PUT_LINE('  a=Math.max(ax.full[0],a);b=Math.min(ax.full[1],b);');
    DBMS_OUTPUT.PUT_LINE('  if(b-a<ax.min){var m=(a+b)/2;a=Math.max(ax.full[0],m-ax.min/2);b=Math.min(ax.full[1],a+ax.min);a=Math.max(ax.full[0],b-ax.min);}');
    DBMS_OUTPUT.PUT_LINE('  ax.dom=[a,b];axDraw(true);');
    DBMS_OUTPUT.PUT_LINE('}');
    DBMS_OUTPUT.PUT_LINE('/* ---- 7. the grid''s scroll: the sticky ruler follows the body, lane captions stay in view */');
    DBMS_OUTPUT.PUT_LINE('function sync(){var b=doc.getElementById(''tl-body''),i=doc.getElementById(''tl-in''),r=$(''#tl > .ruler'');if(!b||!i)return;if(r)r.scrollLeft=b.scrollLeft;i.style.setProperty(''--sl'',b.scrollLeft+''px'');i.style.setProperty(''--vw'',b.clientWidth+''px'');}');
    DBMS_OUTPUT.PUT_LINE('function startAtCurrent(){var b=doc.getElementById(''tl-body'');if(b&&b.scrollWidth>b.clientWidth+2&&!b.scrollLeft)b.scrollLeft=b.scrollWidth;sync();}');
    DBMS_OUTPUT.PUT_LINE('/* ---- boot */');
    DBMS_OUTPUT.PUT_LINE('doc.addEventListener(''DOMContentLoaded'',function(){');
    DBMS_OUTPUT.PUT_LINE('  tip=doc.getElementById(''tip'');if(!tip){tip=mk(''div'','''',doc.body);tip.id=''tip'';tip.setAttribute(''role'',''tooltip'');tip.hidden=true;}');
    DBMS_OUTPUT.PUT_LINE('  $$(''.sw[data-wc]'').forEach(function(s){s.style.setProperty(''--sw'',wcol(s.getAttribute(''data-wc'')));});');
    DBMS_OUTPUT.PUT_LINE('  AX=(window.AWR_DATA||{}).ashx||null;');
    DBMS_OUTPUT.PUT_LINE('  lanes();');
    DBMS_OUTPUT.PUT_LINE('  activity();');
    DBMS_OUTPUT.PUT_LINE('  axInit();');
    DBMS_OUTPUT.PUT_LINE('  var b=doc.getElementById(''tl-body'');if(b)b.addEventListener(''scroll'',sync,{passive:true});');
    DBMS_OUTPUT.PUT_LINE('  var tl=doc.getElementById(''tl'');if(tl&&W.render)W.render(tl);');
    DBMS_OUTPUT.PUT_LINE('  setTimeout(function(){axDraw(true);startAtCurrent();},60);');
    DBMS_OUTPUT.PUT_LINE('  var rt=null;window.addEventListener(''resize'',function(){if(rt)clearTimeout(rt);rt=setTimeout(function(){axDraw();sync();},120);});');
    DBMS_OUTPUT.PUT_LINE('});');
    DBMS_OUTPUT.PUT_LINE('})();');
    DBMS_OUTPUT.PUT_LINE('</script>');
END;
/
