"""Path helpers: repo layout constants + the report-serving safety check.

Everything the server writes lives under server/data/ (gitignored); the
server never writes anywhere else in the repo.  The one path it *reads*
outside its own tree is reports/ (generated by the CLI wrappers), and the
one thing it must get right is refusing to serve anything outside that
directory -- see safe_report_path().
"""

import re
from pathlib import Path

# server/app/paths.py -> app/ -> server/ -> repo root
REPO_ROOT = Path(__file__).resolve().parents[2]

SERVER_DIR = REPO_ROOT / "server"
DATA_DIR = SERVER_DIR / "data"
RUNS_DIR = DATA_DIR / "runs"
TMP_DIR = DATA_DIR / "tmp"
LOCK_FILE = DATA_DIR / "server.lock"
STATE_FILE = DATA_DIR / "state.json"

REPORTS_DIR = REPO_ROOT / "reports"

# Filenames the server is willing to serve under /reports/<file>. Must be
# checked BEFORE the path is joined to REPORTS_DIR, and the joined+resolved
# path must be verified to still live under REPORTS_DIR afterwards -- belt
# and suspenders against '..'  and symlink escapes.
_REPORT_FILENAME_RE = re.compile(r"^[A-Za-z0-9._-]+\.html$")


def ensure_data_dirs(data_dir=None):
    """Create <data_dir>/{,runs,tmp} with owner-only perms if missing.

    Defaults to the real server/data/ (DATA_DIR) but is overridable so
    callers driving an isolated data dir (tests, a future multi-instance
    setup) never touch the real one as a side effect.
    """
    base = Path(data_dir) if data_dir is not None else DATA_DIR
    for d in (base, base / "runs", base / "tmp"):
        d.mkdir(mode=0o700, parents=True, exist_ok=True)
        try:
            d.chmod(0o700)
        except OSError:
            pass


def safe_report_path(filename, reports_dir=None):
    """Return the absolute Path for a report filename, or None if unsafe.

    Two independent checks, both required:
      1. the filename (not the whole request path) must fullmatch
         [A-Za-z0-9._-]+\\.html -- no '/', no '..', no leading dot tricks.
      2. the resolved absolute path must sit inside the resolved
         reports_dir (guards against a symlink planted inside reports/).

    `reports_dir` defaults to the module-level REPORTS_DIR (the real
    repo-root reports/) but is overridable so tests can point at an
    isolated temp directory instead.
    """
    if filename is None:
        return None
    if not _REPORT_FILENAME_RE.fullmatch(filename):
        return None
    reports_dir = Path(reports_dir) if reports_dir is not None else REPORTS_DIR
    base = reports_dir.resolve()
    candidate = (reports_dir / filename).resolve()
    try:
        candidate.relative_to(base)
    except (ValueError, OSError):
        return None
    return candidate


def is_under(path, base_dir):
    """True if resolved `path` sits inside resolved `base_dir`."""
    try:
        Path(path).resolve().relative_to(Path(base_dir).resolve())
        return True
    except (ValueError, OSError):
        return False
