#!/usr/bin/env python3
"""
Generate the DEMO report: a synthetic "very busy production database" run
of awr_trend.sql over a 3-month span with a few releases / upgrades
marked on the timelines.

No Oracle needed.  The page chrome (CSS, shared JS) is lifted verbatim
from the SQL sources so it never drifts from the real report; each
section's markup is a hand-ported twin of the corresponding sql/NN_*.sql
emitter, fed from one coherent hourly model (awrdemo/model.py).

    python3 demo/gen_demo_report.py                # -> docs/examples/demo_busy_db.html
    python3 demo/gen_demo_report.py out.html       # explicit output path
    python3 demo/gen_demo_report.py --cdn out.html # link ECharts from the CDN instead of inlining

See demo/README.md.
"""
from __future__ import annotations

import importlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from awrdemo import chrome                       # noqa: E402
from awrdemo.model import world                  # noqa: E402

ROOT = chrome.ROOT
DEFAULT_OUT = os.path.join(ROOT, "docs", "examples", "demo_busy_db.html")

# (module name, AWR-SECTION tag) in driver order -- sql/awr_trend.sql's
# @@-include order, which is the VISUAL order since v1.5.0 (phase 4):
# Triage, Workload, SQL, Storage & config; 18 before 17 like the driver.
SECTIONS = [
    ("s00_params", "00_params"),
    ("s10_db_time_summary", "10_db_time_summary"),
    ("s08_overview", "08_overview"),
    ("s09_ash_timeline", "09_ash_timeline"),
    ("s07_summary", "07_summary"),
    ("s01_windows", "01_windows"),
    ("s16_day_profile", "16_day_profile"),
    ("s13_utilization", "13_utilization"),
    ("s02_load_profile", "02_load_profile"),
    ("s03_sysmetric", "03_sysmetric"),
    ("s04_waits_fg", "04_waits_fg"),
    ("s05_waits_bg", "05_waits_bg"),
    ("s06_top_sql", "06_top_sql"),
    ("s11_top_sql_ash_breakdown", "11_top_sql_ash_breakdown"),
    ("s18_sqlmon", "18_sqlmon"),
    ("s14_segment_io", "14_segment_io"),
    ("s15_file_io", "15_file_io"),
    ("s12_param_changes", "12_param_changes"),
    ("s17_narrative", "17_narrative"),
]


def marker(tag: str, which: str) -> str:
    return f"<!-- AWR-SECTION: {tag} {which} -->"


def prologue(w, echarts_src: str) -> str:
    """awr_trend.sql lines 512-538: <!DOCTYPE> .. the marker include."""
    out = []
    out.append("<!DOCTYPE html>")
    out.append('<html lang="en"><head><meta charset="utf-8">')
    out.append('<meta name="viewport" content="width=device-width, initial-scale=1">')
    out.append("<title>AWR Timeline Comparison &mdash; run " + w.run_id + "</title>")
    out.append(chrome.style_block())
    out.append("</head><body>")
    out.append('<script src="' + echarts_src
               + '" onerror="document.body.classList.add(\'no-charts\')"></script>')
    if echarts_src.startswith("http"):
        out.append('<div class="cdn-warn">Charts hidden: the ECharts CDN (cdn.jsdelivr.net) '
                   'could not be reached. Tables still show every number.</div>')
    else:
        out.append('<div class="cdn-warn">Charts hidden: the ECharts library could not be '
                   'loaded. Tables still show every number.</div>')
    out.append("<script>window.AWR_DATA = window.AWR_DATA || {};</script>")
    out.append(chrome.lib_script("js_wait_colors.plsql"))
    out.append(chrome.lib_script("js_sparkline.plsql"))
    out.append(chrome.lib_script("js_markers.plsql"))
    # sql/lib/markers_inline.sql: one push per milestone
    for t, label in w.markers:
        lbl = label.replace("\\", "\\\\").replace('"', '\\"').replace("</", "<\\/")
        out.append('<script>window.AWR_MARKERS.push({t:"' + t.strftime("%Y-%m-%d %H:%M")
                   + '",label:"' + lbl + '"});</script>')
    return "\n".join(out) + "\n"


def epilogue(w) -> str:
    return ('</main>\n<footer class="report">\n'
            "Generated by awr_trend.sql v" + w.awr_version
            + " &mdash; run " + w.run_id
            + " &mdash; read-only against the source database, no scratch schema.\n"
            "</footer>\n</body></html>\n")


def render(w, echarts_src: str, only: set | None = None) -> str:
    parts = [prologue(w, echarts_src)]
    for mod_name, tag in SECTIONS:
        if only and tag not in only:
            continue
        try:
            mod = importlib.import_module("awrdemo.sections." + mod_name)
        except ModuleNotFoundError:
            parts.append(marker(tag, "BEGIN") + "\n"
                         + f"<!-- demo: section {tag} not ported yet -->\n"
                         + marker(tag, "END") + "\n")
            continue
        body = mod.emit(w)
        if not body.endswith("\n"):
            body += "\n"
        parts.append(body)
    parts.append(epilogue(w))
    return "".join(parts)


def inline_echarts(html: str, src_rel: str) -> str:
    """run_awr_trend.sh's inline_echarts: splice vendor/echarts.min.js in
    place of the <script src=...> tag for a self-contained file."""
    tag = '<script src="' + src_rel + '" onerror="document.body.classList.add(\'no-charts\')"></script>'
    with open(os.path.join(ROOT, src_rel), encoding="utf-8") as fh:
        js = fh.read()
    return html.replace(tag, "<script>\n" + js + "\n</script>", 1)


def main(argv):
    args = [a for a in argv if not a.startswith("--")]
    flags = {a for a in argv if a.startswith("--")}
    out_path = args[0] if args else DEFAULT_OUT
    w = world()
    if "--cdn" in flags:
        src = "https://cdn.jsdelivr.net/npm/echarts@5/dist/echarts.min.js"
    else:
        src = w.echarts
    only = None
    for f in flags:
        if f.startswith("--only="):
            only = set(f[len("--only="):].split(","))
    html = render(w, src, only)
    if "--cdn" not in flags and "--no-inline" not in flags:
        html = inline_echarts(html, src)
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(html)
    print(f"wrote {out_path} ({len(html.encode('utf-8'))/1024:.0f} KB)")


if __name__ == "__main__":
    main(sys.argv[1:])
